post_install_script = '''
#!/bin/bash -ex

systemctl enable mount_luks.service
systemctl stop mount_luks.service

systemctl enable cosmian_vm_agent.service
systemctl stop cosmian_vm_agent.service
systemctl daemon-reload

'''

post_uninstall_script = '''
#!/bin/bash -ex

systemctl stop mount_luks.service
systemctl disable mount_luks.service

systemctl stop cosmian_vm_agent.service
systemctl disable cosmian_vm_agent.service
systemctl daemon-reload

'''
