#!/bin/bash

set -ex

supervisorctl start cosmian_vm_agent

# wait for cert and key to be generated by `cosmian_vm_agent` before starting nginx
until [ -f /var/lib/cosmian_vm/data/cert.pem ]; do sleep 1; done

# RHEL fix permissions for fresh generated certificate/key
if command -v restorecon &>/dev/null; then
  restorecon /var/lib/cosmian_vm/data/*.pem
fi

systemctl start nginx
