---
# Pre-requisites:
# pip install pre-commit conventional-pre-commit
# pre-commit install
# pre-commit install --install-hooks -t commit-msg
# pre-commit autoupdate

# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
exclude: crate/agent/data|resources|crate/client/src/client.rs
repos:
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v3.2.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: [] # optional: list of Conventional Commits types to allow e.g. [feat, fix, ci, chore, test]

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        stages: [commit]
        exclude_types:
          - yaml
          - markdown

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.39.0
    hooks:
      - id: markdownlint-fix
        args: [--disable=MD004, --disable=MD013, --disable=MD024, --disable=MD029, --disable=MD033, --disable=MD041, --disable=MD046]
        exclude: documentation/docs

  - repo: https://github.com/Lucas-C/pre-commit-hooks-nodejs
    rev: v1.1.2
    hooks:
      - id: htmlhint
      - id: dockerfile_lint
      - id: markdown-toc

  - repo: https://github.com/tcort/markdown-link-check
    rev: v3.12.1
    hooks:
      - id: markdown-link-check
        args: [-q]

  - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
    rev: 0.2.3
    hooks:
      - id: yamlfmt
        args: [--mapping, '2', --sequence, '4', --offset, '2']
        exclude: ansible

  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.35.1
    hooks:
      - id: yamllint
        args: [--format, parsable, --strict]

  - repo: https://github.com/ansible/ansible-lint.git
    rev: v24.2.1
    hooks:
      - id: ansible-lint
        additional_dependencies:
          - ansible

  - repo: https://github.com/crate-ci/typos
    rev: v1.20.3
    hooks:
      - id: typos

  - repo: https://github.com/sirosen/texthooks
    rev: 0.6.6
    hooks:
      - id: fix-smartquotes
      - id: fix-ligatures
      - id: fix-spaces
      - id: forbid-bidi-controls
      - id: macro-expand

  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 3.0.0
    hooks:
      - id: shellcheck

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-byte-order-marker
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-json
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-toml
      - id: check-vcs-permalinks
      - id: check-xml
      - id: check-yaml
      - id: debug-statements
      - id: destroyed-symlinks
      - id: detect-private-key
      - id: double-quote-string-fixer
      - id: end-of-file-fixer
      - id: file-contents-sorter
      - id: fix-byte-order-marker
      - id: fix-encoding-pragma
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: name-tests-test
      - id: requirements-txt-fixer
      - id: sort-simple-yaml
      - id: trailing-whitespace

  - repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
      - id: black
        # avoid clash with `double-quote-string-fixer`
        args: [--skip-string-normalization]

  - repo: https://github.com/Cube707/mkdocs
    rev: e8733d1373c1543d6052925d3272b2ff51dbb140
    hooks:
      - id: mkdocs-build
        additional_dependencies:
          - mkdocs-plugin-progress
          - mkdocs-kroki-plugin
          - mkdocs-material
          - mkdocs-meta-descriptions-plugin
          - markdown-katex
        entry: bash -c 'cd documentation && mkdocs build --strict'

  - repo: https://github.com/Cosmian/git-hooks.git
    rev: v1.0.25
    hooks:
      - id: cargo-format
      # - id: dprint-toml-fix
      # - id: cargo-upgrade
      # - id: cargo-update
      - id: cargo-machete
      - id: cargo-tests-all
      - id: cargo-audit
      - id: cargo-outdated
      - id: clippy-autofix-all
      - id: clippy-autofix-pedantic
      - id: clippy-autofix-others
      - id: clippy-all-targets-all-features
      - id: cargo-format # in last due to clippy fixes

  - repo: https://github.com/cisagov/pre-commit-packer
    rev: v0.0.2
    hooks:
      - id: packer_validate
      - id: packer_fmt
        args: [-write=true]
