[workspace]
members = ["crate/agent", "crate/cli", "crate/client", "crate/ima"]
resolver = "2"

[profile.release]
lto = true
strip = true

[profile.dev]
lto = true
strip = true

[workspace.dependencies]
hex = "0.4"
sha1 = "0.10"
tee_attestation = { git = "https://github.com/Cosmian/tee-tools", branch = "fix_gcp" }
thiserror = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.96"
