[workspace]
members = ["crate/agent", "crate/cli", "crate/client", "crate/ima"]
resolver = "2"

[profile.release]
lto = true
strip = true

# [profile.dev]
# lto = true
# strip = true

[workspace.dependencies]
anyhow = "1.0"
hex = "0.4"
sha1 = "0.10"
sha2 = "0.10"
# ratls = { path = "../microservice_encryption/tee-tools/ratls" }
# tee_attestation = { path = "../microservice_encryption/tee-tools/tee_attestation" }
ratls = { git = "https://github.com/Cosmian/tee-tools", branch = "get_quote" }
tee_attestation = { git = "https://github.com/Cosmian/tee-tools", branch = "get_quote" }
thiserror = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.96"
