---
# tasks file for ansible/roles/configure_ima

- name: Check OS distribution
  debug:
    var: ansible_distribution

- name: Create ima folder
  file:
    path: /etc/ima
    state: directory
    owner: root
    group: root
    mode: "0700"

- name: Copy ima policy
  ansible.builtin.copy:
    src: /tmp/ima-policy
    dest: /etc/ima/
    remote_src: true
    owner: root
    group: root
    mode: "0400"

# Hash and template method
- name: Set hash and template method
  replace:
    path: /etc/default/grub
    regexp: '^(GRUB_CMDLINE_LINUX="[^"]*)(")$'
    replace: '\1 ima_hash=sha256 ima_template=ima-ng\2'

# Update grub
- name: Cerbot and Nginx install on Ubuntu
  when: ansible_distribution == 'Ubuntu'
  block:
    - name: Update grub
      ansible.builtin.command:
        cmd: update-grub

- name: Cerbot and Nginx install on RedHat
  when: ansible_distribution == 'RedHat' or ansible_distribution == 'CentOS' or ansible_distribution == 'Rocky'
  block:
    - name: Update grub
      ansible.builtin.command:
        cmd: grub2-mkconfig -o "$(readlink -e /etc/grub2.conf)"

    - name: Selinux
      ansible.builtin.command:
        cmd: setsebool -P httpd_can_network_connect 1
