---
# tasks file for ansible/roles/configure_ima

- name: Create ima folder
  file:
    path: /etc/ima
    state: directory
    owner: root
    group: root
    mode: "0700"

- name: Copy ima policy
  ansible.builtin.copy:
    src: /tmp/ima-policy
    dest: /etc/ima/
    remote_src: true
    owner: root
    group: root
    mode: "0400"

# Hash and template method
- name: Set hash and template method
  lineinfile:
    path: /etc/default/grub
    regex: 'GRUB_CMDLINE_LINUX="'
    line: 'GRUB_CMDLINE_LINUX="ima_hash=sha256 ima_template=ima-ng"'
    insertafter: "GRUB_CMDLINE_LINUX_DEFAULT"
    state: present
    backup: yes

# Update grub
- name: Update grub
  ansible.builtin.command:
    cmd: update-grub
