---
# tasks file for ansible/roles/configure_ima

- name: Check OS distribution
  ansible.builtin.debug:
    var: ansible_distribution

- name: Check grub file path
  ansible.builtin.stat:
    path: /etc/default/grub
  register: file_check
  tags: azure_security_check

- name: Create ima folder
  ansible.builtin.file:
    path: /etc/ima
    state: directory
    owner: root
    group: root
    mode: "0500"

- name: Copy ima policy
  ansible.builtin.template:
    src: ima-policy.j2
    dest: /etc/ima/ima-policy
    owner: root
    group: root
    mode: "0400"

- name: Override ima policy for RedHat
  when: ansible_distribution == 'RedHat'
  ansible.builtin.template:
    src: ima-policy-selinux.j2
    dest: /etc/ima/ima-policy
    owner: root
    group: root
    mode: "0400"

- name: Copy the bash script to the remote host (in order to update the grub conf)
  when: file_check.stat.exists
  tags: azure_security_check
  ansible.builtin.copy:
    content: |
      #!/usr/bin/bash
      f=/etc/default/grub

      # Template policy
      if grep -q ima_policy= $f ; then
        # Template policy already set
        sed -i 's/ima_policy=[^ "]\+/ima_policy=tcb/' $f
      else
        # Template policy not set
        sed -i /GRUB_CMDLINE_LINUX=/s/\"$/\ ima_policy=tcb\"/ $f
      fi

      # Hash method
      if grep -q ima_hash= $f ; then
        echo "Hash method already set"
        sed -i 's/ima_hash=[^ "]\+/ima_hash=sha256/' $f
      else
        echo "Hash method not set"
        sed -i /GRUB_CMDLINE_LINUX=/s/\"$/\ ima_hash=sha256\"/ $f
      fi

      # Template format
      if grep -q ima_template= $f ; then
        echo "Template format already set"
        sed -i 's/ima_template=[^ "]\+/ima_template=ima-ng/' $f
      else
        echo "Template format not set"
        sed -i /GRUB_CMDLINE_LINUX=/s/\"$/\ ima_template=ima-ng\"/ $f
      fi

      # Console ttyS0
      if grep -q console= $f ; then
        echo "console already set"
        sed -i 's/console=[^ "]\+/console=ttyS0/' $f
      else
        echo "console not set"
        sed -i /GRUB_CMDLINE_LINUX=/s/\"$/\ console=ttyS0\"/ $f
      fi

      # earlyprintk
      if grep -q earlyprintk= $f ; then
        echo "earlyprintk already set"
        sed -i 's/earlyprintk=[^ "]\+/earlyprintk=ttyS0/' $f
      else
        echo "earlyprintk not set"
        sed -i /GRUB_CMDLINE_LINUX=/s/\"$/\ earlyprintk=ttyS0\"/ $f
      fi
    dest: /tmp/grub.sh
    mode: "0700" # Make the script executable
    remote_src: true

- name: Insert/update missing line if default grub does not exist
  when: not file_check.stat.exists
  ansible.builtin.blockinfile:
    path: /etc/default/grub.d/50-cloudimg-settings.cfg
    block: |
      GRUB_CMDLINE_LINUX="ima_policy=tcb ima_hash=sha256 ima_template=ima-ng console=ttyS0 earlyprintk=ttyS0"
  tags: cloudimg

- name: Install packages for Azure
  ansible.builtin.apt:
    name: grub2-common
    state: present
    update_cache: true
  when: not file_check.stat.exists

- name: Update the grub configuration
  when: file_check.stat.exists
  tags: azure_security_check
  ansible.builtin.command: /tmp/grub.sh
  register: cmd_output
  changed_when: cmd_output.rc != 0

- name: Remove the update grub configuration script
  when: file_check.stat.exists
  ansible.builtin.file:
    path: /tmp/grub.sh
    state: absent

- name: Update grub on RedHat
  when: ansible_distribution == 'RedHat'
  tags: azure_security_check
  block:
    - name: Install missing packages
      ansible.builtin.dnf:
        name:
          - grub2-efi
          - grub2-efi-modules
          - shim
        state: present

    - name: Update grub
      ansible.builtin.command:
        cmd: |
          grub2-mkconfig -o /boot/grub2/grub.cfg
      register: cmd_output
      changed_when: cmd_output.rc != 0

    - name: Selinux - allow https
      ansible.builtin.command: setsebool -P httpd_can_network_connect 1
      register: cmd_output
      changed_when: cmd_output.rc != 0
      tags: selinux

- name: Mount a tmpfs volume
  ansible.posix.mount:
    src: tmpfs
    path: /var/tmp
    opts: size=1G
    state: present
    fstype: tmpfs
