[agent]
pem_certificate = "/etc/letsencrypt/live/COSMIAN_VM_DN_PLACEHOLDER/cert.pem"

[app]
service_app_name = "cosmian_helloworld"
decrypted_folder = "/mnt/cosmian_vm/data"
encrypted_secret_app_conf = "/etc/cosmian_vm/app_secrets.json"
