[agent]
# The `cosmian_vm_agent` listens on that host
host = "0.0.0.0"
# The `cosmian_vm_agent` listens on that port
port = 5355
# The location of the SSL certificate used to communicate with the `cosmian_vm_agent`
# It is recommended to put that file inside an encrypted filesystem
# If the path is relative, the location path will be joined with '/var/lib/cosmian_vm/'
ssl_certificate = "data/cert.pem"
# The location of the SSL private key used to communicate with the `cosmian_vm_agent`
# It is recommended to put that file inside an encrypted filesystem
# If the path is relative, the location path will be joined with '/var/lib/cosmian_vm/'
ssl_private_key = "data/key.pem"
# The TPM device path
tpm_device = "/dev/tpmrm0"

[app]
# The service type monitoring the user application
# Possible values: supervisor|systemd|standalone
service_type = "supervisor"
# The name of the service monitoring the used application
service_name = "cosmian_helloworld"
# The location of the user application data
# It is recommended to put that directory inside an encrypted filesystem
# If the path is relative, the location path will be joined with '/var/lib/cosmian_vm/'
app_storage = "data/app"
