---
# tasks file for ansible/roles/instance_configs

- name: Copy instance_configs.cfg
  ansible.builtin.template:
    src: instance_configs.cfg.j2
    dest: /etc/default/instance_configs.cfg
    owner: root
    group: root
    mode: "0644"
