---
# tasks file for launch

- name: Make sure a Supervisor service is running
  when: ansible_distribution == 'Ubuntu'
  ansible.builtin.systemd_service:
    name: supervisor
    state: started
  tags: launch

- name: Make sure a Supervisor service is running
  when: ansible_distribution == 'RedHat' or ansible_distribution == 'CentOS' or ansible_distribution == 'Rocky'
  ansible.builtin.systemd_service:
    name: supervisord
    state: started
  tags: launch

- name: Start Cosmian VM Agent
  community.general.supervisorctl:
    name: cosmian_vm_agent
    state: started
  tags: launch

- name: Wait certificate is generated /var/lib/cosmian_vm/data/cert.pem
  ansible.builtin.wait_for:
    path: /var/lib/cosmian_vm/data/cert.pem
    state: present

- name: Check if port 5555 is listening
  ansible.builtin.wait_for:
    port: 5555
    delay: 5
    timeout: 30
    msg: Timeout waiting for 5555 to respond
  tags:
    - listening
    - listening_cosmian_vm

- name: Check Cosmian VM Agent is OK
  ansible.builtin.uri:
    url: https://localhost:5555/ima/ascii
    validate_certs: false
  tags: listening

- name: Read LUKS password
  ansible.builtin.slurp:
    src: /var/lib/cosmian_vm/data/luks_password
  register: luks_password

- name: Display LUKS password
  ansible.builtin.debug:
    var: "{{ luks_password['content'] | b64decode }}"

- name: Reboot since all checks pass
  ansible.builtin.reboot:
    connect_timeout: 3600
    reboot_timeout: 3600
