[agent]
host = "0.0.0.0"
port = 5355
ssl_certificate = "/var/lib/cosmian_vm/cert.pem"
ssl_private_key = "/var/lib/cosmian_vm/key.pem"

[app]
service_type = "standalone"
service_app_name = "cosmian_helloworld"
decrypted_folder = "/mnt/cosmian_vm/data"
encrypted_secret_app_conf = "/etc/cosmian_vm/app_secrets.json"
