[package]
name = "ima"
version = "0.1.0"
edition = "2021"
license = "MIT/Apache-2.0"
description = "IMA parser"

[dependencies]
bincode = "1.3"
cosmian_vm_client = { path = "../client" }
hex = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sha1 = { workspace = true }
thiserror = { workspace = true }
