---
# tasks file for KMS startup

- name: Make sure a Supervisor service is running
  ansible.builtin.systemd_service:
    state: started
    name: supervisor
  tags: launch

- name: Run Redis
  ansible.builtin.systemd_service:
    state: started
    name: redis

- name: Check if port 6379 is listening
  ansible.builtin.wait_for:
    port: 6379
    delay: 5
    timeout: 30
    msg: Timeout waiting for 6379 to respond

- name: Start Cosmian VM agent
  community.general.supervisorctl:
    name: cosmian_vm_agent
    state: started
  tags: launch

- name: Check if port 5355 is listening
  ansible.builtin.wait_for:
    port: 5355
    delay: 5
    timeout: 30
    msg: Timeout waiting for 5355 to respond
  tags: launch

- name: Check Cosmian VM Agent is OK
  ansible.builtin.uri:
    url: https://localhost:5355/ima/ascii
    validate_certs: false
  tags: listening

- name: Read LUKS password
  ansible.builtin.slurp:
    src: /var/lib/cosmian_vm/data/luks_password
  register: luks_password

- name: Display LUKS password
  ansible.builtin.debug:
    var: "{{ luks_password['content'] | b64decode }}"

- name: Run Nginx
  ansible.builtin.systemd_service:
    state: restarted
    name: nginx

- name: Creates app directory
  ansible.builtin.file:
    path: /var/lib/cosmian_vm/data/app
    state: directory
    owner: root
    group: root
    mode: "0644"

- name: Download Cosmian VM CLI
  ansible.builtin.get_url:
    url: https://package.cosmian.com/cosmian_vm/1.1.0-rc.4/cosmian_vm
    dest: /usr/sbin/
    mode: "0500"
    group: root
    owner: root

- name: Copy KMS configuration
  ansible.builtin.template:
    src: kms.toml.j2
    dest: /tmp/kms.toml
    mode: "0500"
    owner: root
    group: root

- name: Cosmian VM App initialization
  ansible.builtin.command:
    cmd: |
      cosmian_vm --url https://localhost:5355 --allow-insecure-tls app init -c /tmp/kms.toml
  register: cosmian_vm_output
  ignore_errors: true
  tags: app_init

- name: Display agent logs variable
  ansible.builtin.debug:
    var: cosmian_vm_output
  tags: app_init

- name: Read Cosmian VM agent logs
  ansible.builtin.slurp:
    src: /var/log/cosmian_vm/agent.out.log
  register: agent_logs
  tags: app_init

- name: Display Agent logs
  ansible.builtin.debug:
    var: "{{ agent_logs['content'] | b64decode }}"
  tags: app_init

- name: Fail if Cosmian app init has failed previously
  ansible.builtin.fail:
    msg: Cosmian app init failed with return code {{ cosmian_vm_output }}
  when:
    - cosmian_vm_output is defined
    - cosmian_vm_output.rc is defined
    - cosmian_vm_output.rc != 0
  tags: app_init

- name: Override KMS supervisor configuration with autostart to true
  when: ansible_distribution == 'Ubuntu'
  ansible.builtin.lineinfile:
    path: /etc/supervisor/conf.d/cosmian_kms.conf
    regexp: autostart=false
    line: autostart=true
    backup: true

- name: Override KMS supervisor configuration with autostart to true
  when: ansible_distribution == 'RedHat' or ansible_distribution == 'CentOS' or ansible_distribution == 'Rocky'
  ansible.builtin.lineinfile:
    path: /etc/supervisord.d/cosmian_kms.ini
    regexp: autostart=false
    line: autostart=true
    backup: true

- name: Start KMS
  community.general.supervisorctl:
    name: cosmian_kms
    state: started
  tags: launch

- name: Run Nginx
  ansible.builtin.systemd_service:
    state: restarted
    name: nginx

- name: Check if port 8080 is listening
  ansible.builtin.wait_for:
    port: 8080
    delay: 5
    timeout: 30
    msg: Timeout waiting for 8080 to respond
  tags: listening

- name: Check if port 443 is listening
  ansible.builtin.wait_for:
    port: 443
    delay: 5
    timeout: 30
    msg: Timeout waiting for 443 to respond
  tags: listening

- name: Check KMS returns its version
  ansible.builtin.uri:
    url: http://localhost:8080/version
  tags: listening

- name: Check KMS returns its version on HTTPS
  ansible.builtin.uri:
    url: https://localhost/version
    validate_certs: false
  tags: listening
