---
# tasks file for cleanup

- name: Get supervisor Status
  ansible.builtin.systemd:
    name: supervisor
  register: supervisor_status

- debug:
    var: supervisor_status.status.ActiveState

- name: Check if /etc/supervisor/conf.d/cosmian_vm_agent.conf exists
  stat:
    path: /etc/supervisor/conf.d/cosmian_vm_agent.conf
  register: cosmian_supervisor_conf_check

- name: Stop Cosmian VM Agent if it exists
  community.general.supervisorctl:
    name: cosmian_vm_agent
    state: stopped
  when:
    - cosmian_supervisor_conf_check.stat.exists
    - supervisor_status.status.ActiveState=='active'

- name: Check if /dev/mapper/cosmian_vm_container exists
  stat:
    path: /dev/mapper/cosmian_vm_container
  register: volume_check

- name: Umount Cosmian VM LUKS volume
  ansible.posix.mount:
    path: /dev/mapper/cosmian_vm_container
    state: absent
  when: volume_check.stat.exists

- name: Check if /var/lib/cosmian_vm/data exists
  stat:
    path: /var/lib/cosmian_vm/data
  register: data_volume_check

- name: Umount Cosmian VM LUKS data volume
  ansible.posix.mount:
    path: /var/lib/cosmian_vm/data
    state: absent
  when: data_volume_check.stat.exists

- name: Check if /var/lib/cosmian_vm/tmp exists
  stat:
    path: /var/lib/cosmian_vm/tmp
  register: tmpfs_volume_check

- name: Umount the tmpfs volume
  ansible.posix.mount:
    path: /var/lib/cosmian_vm/tmp
    state: absent
  when: tmpfs_volume_check.stat.exists

# using native-ansible `file` task does not fail on error
- name: Clean Cosmian VM existing folders
  ansible.builtin.command:
    cmd: |
      rm -rf /var/lib/cosmian_vm
      rm -rf /var/log/cosmian_vm
      rm -rf /etc/cosmian_vm
