---
# tasks file for ansible/roles/kms

- name: Check OS distribution
  ansible.builtin.debug:
    var: ansible_distribution

- name: Check Cosmian KMS version
  ansible.builtin.debug:
    var: cosmian_kms_version

- name: Install prerequisites packages
  ansible.builtin.package:
    name:
      - nginx
      - unzip
      - redis
    state: present

- name: Create the directory /usr/local/sbin
  ansible.builtin.file:
    path: /usr/local/sbin
    state: directory
    mode: "0755"
    owner: root
    group: root

- name: Download KMS
  ansible.builtin.get_url:
    url: https://package.cosmian.com/kms/{{ cosmian_kms_version }}/ubuntu_22_04.zip
    dest: /tmp
    mode: "0755"
    group: root
    owner: root

- name: Unarchive binaries
  ansible.builtin.unarchive:
    src: /tmp/ubuntu_22_04.zip
    dest: /tmp
    remote_src: true

- name: Copy KMS executable
  ansible.builtin.copy:
    src: /tmp/ubuntu_22_04/cosmian_kms_server
    dest: /usr/local/sbin/cosmian_kms
    remote_src: true
    owner: root
    group: root
    mode: "0500"

- name: Remove temporary files
  ansible.builtin.file:
    path:
      - /tmp/ubuntu_22_04
      - /tmp/ubuntu_22_04.zip
    state: absent

- name: Add KMS supervisor configuration
  when: ansible_distribution == 'Ubuntu'
  ansible.builtin.template:
    src: supervisor_kms.conf.j2
    dest: /etc/supervisor/conf.d/cosmian_kms.conf
    owner: root
    group: root
    mode: "0644"

- name: Add KMS supervisor configuration
  when: ansible_distribution == 'RedHat' or ansible_distribution == 'CentOS' or ansible_distribution == 'Rocky'
  ansible.builtin.template:
    src: supervisor_kms.conf.j2
    dest: /etc/supervisord.d/cosmian_kms.ini
    owner: root
    group: root
    mode: "0644"

- name: Override Cosmian VM configuration
  ansible.builtin.template:
    src: agent.toml.j2
    dest: /etc/cosmian_vm/agent.toml
    owner: root
    group: root
    mode: "0644"

- name: Create the directory /var/www/html if it does not exist
  ansible.builtin.file:
    path: /var/www/html
    state: directory
    owner: root
    group: root
    mode: "0644"

- name: Selinux - add nginx to permissive allow httpd
  when: ansible_distribution == 'RedHat' or ansible_distribution == 'CentOS' or ansible_distribution == 'Rocky'
  ansible.builtin.command: semanage permissive -a httpd_t
  tags: selinux

- name: Add Nginx configuration
  ansible.builtin.template:
    src: nginx.j2
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: "0644"

- name: Enable systemd Nginx service
  ansible.builtin.systemd_service:
    name: nginx
    enabled: true
    state: stopped
    daemon_reload: true

- name: Make systemd Nginx restarting on failure
  ansible.builtin.blockinfile:
    path: /etc/systemd/system/multi-user.target.wants/nginx.service
    block: |
      [Service]
      Restart=on-failure
      RestartSec=10s
  tags: systemd_nginx

- name: Enable systemd Redis service
  ansible.builtin.systemd_service:
    name: redis
    enabled: true
    state: stopped
    daemon_reload: true
