---
# tasks file for ansible/roles/cosmian_vm_agent

- name: Gathering facts
  tags: install_deb
  ansible.builtin.gather_facts:

- name: Check OS distribution
  ansible.builtin.debug:
    var: ansible_distribution

- name: Check OS version
  ansible.builtin.debug:
    var: ansible_distribution_version

- name: Check package version
  ansible.builtin.debug:
    var: package_version

- name: Check Cosmian VM version
  ansible.builtin.debug:
    var: cosmian_vm_version

- name: Install Cosmian VM via RPM package
  when: ansible_distribution == 'RedHat'
  block:
    - name: Declare package name
      ansible.builtin.set_fact:
        cosmian_vm_package_name: cosmian_vm-{{ package_version }}-1.x86_64.rpm

    - name: Download RPM package from package.cosmian.com
      ansible.builtin.get_url:
        url: https://package.cosmian.com/cosmian_vm/{{ cosmian_vm_version }}/rhel9/{{ package_name }}
        dest: /tmp
        mode: "0755"
        group: root
        owner: root

    - name: Install Cosmian VM RPM package from package.cosmian.com
      ansible.builtin.dnf:
        name: /tmp/{{ package_name }}
        state: present
        disable_gpg_check: true
      tags: install_rpm

- name: Install Cosmian VM via Debian package
  when: ansible_distribution == 'Ubuntu'
  tags: install_deb
  block:
    - name: Declare package name
      ansible.builtin.set_fact:
        cosmian_vm_package_name: cosmian-vm_{{ package_version }}-1_amd64.deb

    - name: Download Debian package from package.cosmian.com
      ansible.builtin.get_url:
        url: https://package.cosmian.com/cosmian_vm/{{ cosmian_vm_version }}/ubuntu-{{ ansible_distribution_version }}/{{ package_name }}
        dest: /tmp
        mode: "0755"
        group: root
        owner: root

    - name: Install Cosmian VM Debian package
      ansible.builtin.apt:
        deb: /tmp/{{ package_name }}
