---
# tasks file for App checkup

- name: Reboot before anything - {{ check_app_name }}
  ansible.builtin.reboot:
    connect_timeout: 3600
    reboot_timeout: 3600
  when: check_app_test_reboot

- name: Start systemd services - {{ check_app_name }}
  when: not check_app_test_reboot
  block:
    - name: Start systemd service - {{ check_app_systemd_name }}
      ansible.builtin.systemd_service:
        name: "{{ check_app_systemd_name }}"
        state: started

    - name: Start systemd service - nginx
      ansible.builtin.systemd_service:
        name: nginx
        state: started

- name: Check SSH remote host IP
  ansible.builtin.debug:
    var: inventory_hostname

- name: Check Cosmian VM Agent version
  ansible.builtin.debug:
    var: cosmian_vm_version

- name: Wait for certificate /var/lib/cosmian_vm/data/cert.pem
  ansible.builtin.wait_for:
    path: /var/lib/cosmian_vm/data/cert.pem
    state: present

- name: Check if port 5555 is listening
  ansible.builtin.wait_for:
    host: "{{ inventory_hostname }}"
    port: 5555
    delay: 5
    timeout: 60
    msg: Timeout waiting for 5555 to respond
  delegate_to: localhost

- name: Before anything - read logs of {{ check_app_name }}
  ansible.builtin.command:
    cmd: |
      journalctl -u {{ check_app_systemd_name }}
  register: app_logs
  tags: launch
  changed_when: app_logs.rc != 0

- name: Display logs of {{ check_app_name }}
  ansible.builtin.debug:
    var: app_logs
  tags: launch

- name: App initialization - sending configuration {{ check_app_configuration_path }}
  ansible.builtin.command:
    cmd: |
      cosmian_vm --url https://{{ inventory_hostname }}:5555 --allow-insecure-tls app init -c {{ check_app_configuration_path }}
  register: cosmian_vm_app_init
  tags: app_init
  ignore_errors: true
  delegate_to: localhost
  become: false
  changed_when: cosmian_vm_app_init.rc != 0

- name: Display CLI logs after app init
  ansible.builtin.debug:
    var: cosmian_vm_app_init
  tags: app_init

- name: App initialization - reading Cosmian VM agent logs
  ansible.builtin.command:
    cmd: |
      journalctl -u cosmian_vm_agent
  register: agent_logs
  tags: app_init
  changed_when: agent_logs.rc != 0

- name: App initialization - displaying Agent logs
  ansible.builtin.debug:
    var: agent_logs
  tags: app_init

- name: Fail if Cosmian app init has failed previously
  ansible.builtin.fail:
    msg: Cosmian snapshot failed with return code {{ cosmian_vm_app_init }}
  when:
    - cosmian_vm_app_init is defined
    - cosmian_vm_app_init.rc is defined
    - cosmian_vm_app_init.rc != 0
  tags: app_init

- name: App restart
  ansible.builtin.command:
    cmd: |
      cosmian_vm --url https://{{ inventory_hostname }}:5555 --allow-insecure-tls app restart
  register: cosmian_vm_app_restart
  tags: app_restart
  delegate_to: localhost
  become: false
  changed_when: cosmian_vm_app_restart.rc != 0

- name: Display CLI logs after app restart
  ansible.builtin.debug:
    var: cosmian_vm_app_restart
  tags: app_restart

- name: App restart - reading Cosmian VM agent logs
  ansible.builtin.command:
    cmd: |
      journalctl -u cosmian_vm_agent
  register: agent_logs
  ignore_errors: true
  tags: app_restart
  changed_when: agent_logs.rc != 0

- name: App restart - displaying Agent logs
  ansible.builtin.debug:
    var: agent_logs
  tags: app_restart

- name: Fail if Cosmian app restart has failed previously
  ansible.builtin.fail:
    msg: Cosmian snapshot failed with return code {{ cosmian_vm_app_restart }}
  when:
    - cosmian_vm_app_restart is defined
    - cosmian_vm_app_restart.rc is defined
    - cosmian_vm_app_restart.rc != 0
  tags: app_restart

- name: Read logs of {{ check_app_name }}
  ansible.builtin.command:
    cmd: |
      journalctl -u {{ check_app_systemd_name }}
  register: app_logs
  tags: after_restart
  changed_when: app_logs.rc != 0

- name: Display logs of {{ check_app_name }}
  ansible.builtin.debug:
    var: app_logs
  tags: launch

- name: Check if port 443 is listening
  ansible.builtin.wait_for:
    host: "{{ inventory_hostname }}"
    port: 443
    delay: 5
    timeout: 30
    msg: Timeout waiting for 443 to respond
  delegate_to: localhost
  become: false
  tags: listening

- name: HTTPS connection - {{ check_app_name }}
  ansible.builtin.uri:
    url: https://{{ inventory_hostname }}/{{ check_app_endpoint[0] }}
    validate_certs: false
  delegate_to: localhost
  become: false
  register: result
  retries: 30
  delay: 10
  until: result.status == 200
  tags: listening,listening_app
  when: (check_app_name == "AI Runner") or (check_app_name == "KMS")

- name: Check endpoint {{ check_app_endpoint[1] }}
  ansible.builtin.uri:
    url: https://{{ inventory_hostname }}/{{ check_app_endpoint[1] }}
    validate_certs: false
    method: POST
    body_format: form-multipart
    return_content: true
    body:
      doc: "Mais, vous savez, moi je ne crois pas
        qu'il y ait de bonne ou de mauvaise situation.
        Moi, si je devais résumer ma vie aujourd'hui avec vous,
        je dirais que c'est d'abord des rencontres,
        Des gens qui m'ont tendu la main,
        peut-être à un moment où je ne pouvais pas, où j'étais seul chez moi.
        Et c'est assez curieux de se dire que les hasards,
        les rencontres forgent une destinée...
        Parce que quand on a le goût de la chose,
        quand on a le goût de la chose bien faite,
        Le beau geste, parfois on ne trouve pas l'interlocuteur en face,
        je dirais, le miroir qui vous aide à avancer.
        Alors ce n'est pas mon cas, comme je le disais là,
        puisque moi au contraire, j'ai pu ;
        Et je dis merci à la vie, je lui dis merci,
        je chante la vie, je danse la vie... Je ne suis qu'amour!
        Et finalement, quand beaucoup de gens aujourd'hui me disent :
        'Mais comment fais-tu pour avoir cette humanité ?',
        Eh bien je leur réponds très simplement,
        je leur dis que c'est ce goût de l'amour,
        Ce goût donc qui m'a poussé aujourd'hui
        à entreprendre une construction mécanique,
        Mais demain, qui sait, peut-être simplement
        à me mettre au service de la communauté,
        à faire le don, le don de soi..."
  delegate_to: localhost
  become: false
  register: result
  retries: 30
  delay: 10
  until: result.status == 200
  tags: second_endpoint
  when: (check_app_name == "AI Runner")

- name: Check endpoint {{ check_app_endpoint[2] }}
  ansible.builtin.uri:
    url: https://{{ inventory_hostname }}/{{ check_app_endpoint[2] }}
    validate_certs: false
    method: POST
    body_format: form-multipart
    return_content: true
    body:
      doc: Hello
      src_lang: en
      tgt_lang: fr
  delegate_to: localhost
  become: false
  register: result
  retries: 30
  delay: 10
  until: result.status == 200
  tags: third_endpoint
  when: (check_app_name == "AI Runner")

- name: Clean Cosmian VM existing folders
  ansible.builtin.command:
    cmd: |
      rm -f cosmian_vm
  delegate_to: localhost
  register: cmd_output
  changed_when: cmd_output.rc != 0
