---
# handlers file for no_updates
- name: Restart APT service
  ansible.builtin.service:
    name: apt-daily.timer
    state: restarted
  when: "'ubuntu' in tags"

- name: Restart DNF service
  ansible.builtin.service:
    name: dnf-automatic.timer
    state: restarted
  when: "'redhat' in tags"
