---
# tasks file for firewall

- name: Open ports on RHEL
  when: ansible_distribution == 'RedHat'
  block:
    - name: Open port 5555
      ansible.posix.firewalld:
        zone: public
        port: 5555/tcp
        permanent: yes
        state: enabled

    - name: Open port 8080 for KMS
      ansible.posix.firewalld:
        zone: public
        port: 8080/tcp
        permanent: yes
        state: enabled

    - name: Open port 80 for HTTP redirect to HTTPS
      ansible.posix.firewalld:
        zone: public
        port: 80/tcp
        permanent: yes
        state: enabled

    - name: Open port 443 for HTTPS
      ansible.posix.firewalld:
        zone: public
        port: 443/tcp
        permanent: yes
        state: enabled

    - name: Always reload firewalld
      ansible.builtin.service:
        name: firewalld
        state: reloaded

    - name: Comment ipv6 ref in /etc/hosts file
      ansible.builtin.template:
        src: hosts
        dest: /etc/hosts
        owner: root
        group: root
        mode: "0644"
