[package]
name = "cosmian_vm_client"
version = "0.1.0"
edition = "2021"
license = "MIT/Apache-2.0"

[dependencies]
hex = { workspace = true }
http = "0.2"
reqwest = { version = "0.11.14", features = ["json", "multipart", "stream"] }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
