[package]
name = "cosmian_vm_client"
version = "0.1.0"
edition = "2021"
license = "MIT/Apache-2.0"

[dependencies]
cosmian_vm_agent = { path = "../agent" }                                      # TODO: don't do that
hex = "0.4"
http = "0.2"
reqwest = { version = "0.11.14", features = ["json", "multipart", "stream"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.96"
thiserror = "1.0"
