[package]
name = "cosmian_vm_client"
version = "0.1.0"
edition = "2021"
license = "MIT/Apache-2.0"

[dependencies]
hex = { workspace = true }
http = "0.2"
ratls = { workspace = true }
# Important: align the rustls version with reqwest rustls dependency
reqwest = { version = "0.11.22", features = [
    "json",
    "multipart",
    "native-tls",
    "rustls-tls",
    "stream",
] }
rustls = { version = "0.21", features = ["dangerous_configuration"] }
serde = { workspace = true }
serde_json = { workspace = true }
tee_attestation = { workspace = true }
thiserror = { workspace = true }
url = "2.2"
webpki-roots = "0.25"
