#!/bin/sh -ex

systemctl unmask mount_luks.service
systemctl enable mount_luks.service
systemctl stop mount_luks.service

systemctl unmask cosmian_vm_agent.service
systemctl enable cosmian_vm_agent.service
systemctl stop cosmian_vm_agent.service

systemctl daemon-reload

#DEBHELPER#
