---
# tasks file for no_updates

- name: Check OS distribution
  ansible.builtin.debug:
    var: ansible_distribution

- name: Disable automatic updates on Ubuntu
  when: ansible_distribution == 'Ubuntu'
  tags: disable_automatic_update
  block:
    - name: Disable auto upgrade services
      ansible.builtin.systemd_service:
        name: "{{ item }}"
        enabled: false
        masked: true
        state: stopped
        daemon_reload: true
      with_items:
        - unattended-upgrades
        - apt-daily
        - apt-daily-upgrade
        - snapd
        - apt-daily-upgrade.timer
        - apt-daily.timer
        - snapd.socket

    - name: Update APT configuration to disable automatic updates
      ansible.builtin.lineinfile:
        path: /etc/apt/apt.conf.d/10periodic
        regexp: 'APT::Periodic::Update-Package-Lists "1";'
        line: 'APT::Periodic::Update-Package-Lists "0";'
        backup: true

    - name: Update APT cache
      ansible.builtin.apt:
        autoclean: true
        update_cache: true

- name: Disable automatic updates on Red Hat
  when: ansible_distribution == 'RedHat'
  tags: disable_automatic_update
  block:
    - name: Populate service facts
      ansible.builtin.service_facts:

    - name: Disable dnf-automatic service
      ansible.builtin.systemd_service:
        name: dnf-automatic.timer
        enabled: false
        state: stopped
        masked: true
        daemon_reload: true
      when: "'dnf-automatic' in services"

    - name: Disable automatic updates in dnf.conf
      ansible.builtin.lineinfile:
        path: /etc/dnf/dnf.conf
        line: "check_update=0"
        backup: true

    - name: Check if automatic.conf exists
      ansible.builtin.stat:
        path: /etc/dnf/automatic.conf
      register: __dnf_automatic_conf

    - name: Update automatic.conf to disable automatic updates download
      ansible.builtin.lineinfile:
        path: /etc/dnf/automatic.conf
        regexp: "download_updates = yes"
        line: "download_updates = no"
        backup: true
      when: __dnf_automatic_conf.stat.exists

    - name: Update automatic.conf to disable automatic updates apply
      ansible.builtin.lineinfile:
        path: /etc/dnf/automatic.conf
        regexp: "apply_updates = yes"
        line: "apply_updates = no"
        backup: true
      when: __dnf_automatic_conf.stat.exists

    - name: Clean dnf metadata
      ansible.builtin.command: dnf clean all
      register: cmd_output
      changed_when: cmd_output.rc != 0

    - name: Update DNF cache
      ansible.builtin.dnf:
        update_cache: true
