---
# tasks file for cleanup

- name: Get Supervisor status
  ansible.builtin.systemd_service:
    name: supervisor
  register: supervisor_status
  tags: stopping_agent

- name: Display Supervisor status
  ansible.builtin.debug:
    var: supervisor_status.status.ActiveState
  tags: stopping_agent

- name: Check if /etc/supervisor/conf.d/cosmian_vm_agent.conf exists
  ansible.builtin.stat:
    path: /etc/supervisor/conf.d/cosmian_vm_agent.conf
  register: cosmian_supervisor_conf_check
  tags: stopping_agent

- name: Stop Cosmian VM Agent if it exists
  community.general.supervisorctl:
    name: cosmian_vm_agent
    state: stopped
  when:
    - cosmian_supervisor_conf_check.stat.exists
    - supervisor_status.status.ActiveState=='active'
  register: stopping_agent
  failed_when:
    - stopping_agent is defined
    - stopping_agent.rc is defined
    - stopping_agent.rc !=0
  tags: stopping_agent

- name: Make sure a Supervisor service is down
  when: ansible_distribution == 'RedHat' or ansible_distribution == 'CentOS' or ansible_distribution == 'Rocky'
  ansible.builtin.systemd_service:
    name: supervisord
    state: stopped
  tags: stopping

- name: Check if /dev/mapper/cosmian_vm_container exists
  ansible.builtin.stat:
    path: /dev/mapper/cosmian_vm_container
  register: volume_check

- name: Umount Cosmian VM LUKS volume
  ansible.posix.mount:
    path: /dev/mapper/cosmian_vm_container
    state: absent
  when: volume_check.stat.exists

- name: Force umount of /var/lib/cosmian_vm/data
  ansible.builtin.command:
    cmd: |
      umount /var/lib/cosmian_vm/data
      cryptsetup close /dev/mapper/cosmian_vm_container
  register: unmounting
  failed_when: unmounting.rc !=128 and unmounting.rc !=96 and unmounting.rc !=0
  tags: umount

- name: Check if /var/lib/cosmian_vm/tmp exists
  ansible.builtin.stat:
    path: /var/lib/cosmian_vm/tmp
  register: tmpfs_volume_check

- name: Umount the tmpfs volume
  ansible.posix.mount:
    path: /var/lib/cosmian_vm/tmp
    state: absent
  when: tmpfs_volume_check.stat.exists

- name: Wait until the volumes are properly unmounted
  ansible.builtin.wait_for:
    path: |
      /var/lib/cosmian_vm/data
      /var/lib/cosmian_vm/tmp
    state: absent

# using native-ansible `file` task does not fail on error
- name: Clean Cosmian VM existing folders
  ansible.builtin.command:
    cmd: |
      rm -rf /var/lib/cosmian_vm
      rm -rf /var/log/cosmian_vm
      rm -rf /etc/cosmian_vm
      rm -f /etc/supervisord.d/cosmian_vm_agent.ini
      rm -f /etc/supervisor/conf.d/cosmian_vm_agent.conf
