---
# tasks file for cleanup

- name: Remove cosmian-vm-agent on Ubuntu
  when: ansible_distribution == 'Ubuntu'
  ansible.builtin.apt:
    name: cosmian-vm-agent
    state: absent

- name: Remove cosmian-vm-agent on RedHat
  when: ansible_distribution == 'RedHat'
  ansible.builtin.dnf:
    name: cosmian_vm_agent
    state: absent

- name: Reboot since systemd services have been disabled
  ansible.builtin.reboot:
    connect_timeout: 3600
    reboot_timeout: 3600
