---
# tasks file for launch

- name: Check Confidential VM compatibility
  ansible.builtin.uri:
    url: http://169.254.169.254/metadata/instance?api-version=2021-02-01
    headers:
      Metadata: true
    method: GET
    return_content: true
    status_code: 200
  register: instance_metadata

- name: Check Instance metadata
  ansible.builtin.debug:
    var: instance_metadata
