---
- name: Clean previous install of Cosmian VM Agent
  hosts: all
  become: true
  roles:
    - check_cpu
    - cleanup_ai_runner
    - cleanup_cosmian_vm_agent

- name: Install base image prerequisites
  ansible.builtin.import_playbook: base-image-packer-playbook.yml

- name: Install AI Runner
  ansible.builtin.import_playbook: ai-runner-packer-playbook.yml

- name: Check AI runner
  hosts: all
  become: true
  environment:
    RUST_LOG: "cosmian_vm=trace"
  roles:
    - role: cosmian_vm
      delegate_to: localhost
      tags:
        - role-cosmian-vm
        - check-ai-runner

    - role: check_app
      check_app_name: AI Runner
      check_app_systemd_name: cosmian_ai_runner
      check_app_endpoint:
        - health
        - summarize
        - translate
      check_app_configuration_path: roles/ai_runner/templates/config.json.j2
      tags: check-ai-runner

    - role: check_cosmian_vm
      tags: check-ai-runner
