---
- name: Setup base image
  hosts: all
  become: true
  roles:
    - role: upgrade
      tags: role-upgrade
    - tpm
    - instance_configs # GCP only
    - intel
    - no_updates
    - role: configure_ima
      tags: role-configure-ima

- name: Reboot after GRUB changes, Linux updates and TPM support installation
  hosts: all
  become: true
  tasks:
    - name: Reboot the system
      ansible.builtin.reboot:
        connect_timeout: 3600
        reboot_timeout: 3600
      when: reboot_allowed

    - name: Check /proc/cmdline
      ansible.builtin.command: cat /proc/cmdline
      register: cmdline
      changed_when: cmdline.rc != 0

    - name: Display /proc/cmdline
      ansible.builtin.debug:
        var: cmdline

    - name: Display Redhat security updates
      when: ansible_distribution == 'RedHat'
      block:
        - name: Display security available updates
          ansible.builtin.shell:
            cmd: |
              dnf updateinfo list security
          register: dnf_security_update
          changed_when: dnf_security_update.rc != 0

        - name: Display Security updates
          ansible.builtin.debug:
            var: dnf_security_update
