---
- name: Setup base image
  hosts: all
  become: true
  roles:
    - role: check_cpu
      tags: role-check-cpu
    - role: upgrade
      tags: role-upgrade
    - role: tpm
      tags: role-tpm
    - role: instance_configs # GCP only
      tags: role-instance-configs
    - role: intel
      tags: role-intel
    - role: no_updates
      tags: role-no-updates
    - role: selinux
      tags: role-selinux
    - role: configure_ima
      tags: role-configure-ima

- name: Reboot after GRUB changes, Linux updates and TPM support installation
  hosts: all
  become: true
  tasks:
    - name: Reboot the system
      ansible.builtin.reboot:
        connect_timeout: 3600
        reboot_timeout: 3600
      when: reboot_allowed

    - name: Check /proc/cmdline
      ansible.builtin.command: cat /proc/cmdline
      register: base_image_packer_playbook_cmdline
      changed_when: base_image_packer_playbook_cmdline.rc != 0

    - name: Display /proc/cmdline
      ansible.builtin.debug:
        var: cmdline

    - name: Display Redhat security updates
      when: ansible_distribution == 'RedHat'
      block:
        - name: Display security available updates
          ansible.builtin.shell:
            cmd: |
              dnf updateinfo list security
          register: base_image_packer_playbook_dnf_security_update
          changed_when: base_image_packer_playbook_dnf_security_update.rc != 0

        - name: Display Security updates
          ansible.builtin.debug:
            var: base_image_packer_playbook_dnf_security_update

- name: Clean base image
  hosts: all
  become: true
  roles:
    - role: cleanup
      tags: role-cleanup
