---
- name: Setup base image
  hosts: all
  become: true
  roles:
    - role: configure_ima
      tags: configure_ima
    - tpm
    - instance_configs # GCP only
    - intel
    - upgrade
    - no_updates

- name: Reboot after GRUB changes, Linux updates and TPM support installation
  hosts: all
  become: true
  tasks:
    - name: Reboot the system
      ansible.builtin.reboot:
        connect_timeout: 3600
        reboot_timeout: 3600

    - name: Check /proc/cmdline
      ansible.builtin.command: cat /proc/cmdline
      register: cmdline
      changed_when: cmdline.rc != 0

    - name: Display /proc/cmdline
      ansible.builtin.debug:
        var: cmdline
