---
- name: Setup Cosmian VM
  hosts: all
  become: true
  roles:
    - check_cpu
    - clevis
    - configure_ima
    - tpm
    - cosmian_vm_agent
    - no_updates
    - instance_configs # GCP only
    - upgrade
