---
- name: Install Cosmian VM Agent
  ansible.builtin.import_playbook: cosmian-vm-packer-playbook.yml

- name: Install KMS
  hosts: all
  become: true
  roles:
    - kms
    - role: cleanup
      tags: role-cleanup
