---
- name: Setup Cosmian VM + KMS
  hosts: all
  become: true
  roles:
    - configure_ima
    - tpm
    - cleanup_cosmian_vm_agent
    - cosmian_vm_agent
    - no_updates
    - instance_configs
    - upgrade
    - cleanup_kms
    - kms
    - start_kms
