---
- name: Setup Cosmian VM + KMS
  hosts: all
  become: true
  roles:
    - configure_ima
    - tpm
    - clean_previous_installation
    - cosmian_vm_agent
    - no_updates
    - instance_configs
    - upgrade
    - launch
    - kms
