[package]
name = "cosmian_vm_agent"
version = "0.4.0"
edition = "2021"

[dependencies]
actix-cors = "0.6"
actix-http = "3"
actix-web = { version = "4", features = ["rustls"] }
actix-web-lab = "0.20"
aes-gcm = { workspace = true }
anyhow = { workspace = true }
cosmian_vm_client = { path = "../client" }
der = { workspace = true }
ecdsa = { workspace = true }
env_logger = "0.11"
gethostname = "0.4"
hex = { workspace = true }
ima = { path = "../ima" }
p256 = { workspace = true }
pep440 = "0.2"
rand_chacha = { workspace = true }
rayon = "1.8"
# Important: align the rustls version with actix rustls dependency
rustls = { version = "0.20", features = ["dangerous_configuration"] }
rustls-pemfile = "1.0"
serde = { workspace = true }
serde_json = { workspace = true }
sha1 = { workspace = true }
sha2 = { workspace = true }
spki = { workspace = true }
sysinfo = "0.29"
tee_attestation = { workspace = true }
thiserror = { workspace = true }
toml = "0.8"
tpm_quote = { workspace = true }
tracing = "0.1"
tss-esapi = "7.4.0"
uuid = { version = "1.3", features = ["serde", "v4"] }
walkdir = "2.4"
x509-cert = { workspace = true }
