[package]
name = "cosmian_vm_agent"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-cors = "0.6"
actix-http = "3"
actix-web = "4"
hex = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.96"
sha1 = "0.10"
tee_attestation = { path = "../../../microservice_encryption/tee-tools/tee_attestation" }
# " git = "https://github.com/Cosmian/tee-tools", branch = "get_quote" }
thiserror = "1.0"
tracing = "0.1"
tracing-actix-web = "0.7"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
uuid = { version = "1.3", features = ["serde", "v4"] }
walkdir = "2.4"
