[package]
name = "cosmian_vm_agent"
version = "0.1.0"
edition = "2021"

[dependencies]
aes-gcm = "0.10"
anyhow = { workspace = true }
actix-cors = "0.6"
actix-http = "3"
actix-web = "4"
cosmian_vm_client = { path = "../client" }
hex = { workspace = true }
ima = { path = "../ima" }
sha1 = { workspace = true }
sha2 = { workspace = true }
tee_attestation = { workspace = true }
thiserror = { workspace = true }
tracing = "0.1"
tracing-actix-web = "0.7"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
uuid = { version = "1.3", features = ["serde", "v4"] }
walkdir = "2.4"
