[package]
name = "cosmian_vm_agent"
version = "1.1.0"
edition = "2021"
license-file = "../../LICENSE.md"

[lib]
# doc test linking as a separate binary is extremely slow
# and is not needed for internal lib
doctest = false

[dependencies]
actix-cors = "0.6"
actix-http = "3"
actix-web = { version = "4", features = ["rustls"] }
actix-web-lab = "0.20"
awc = "3.4"
anyhow = { workspace = true }
const_format = "0.2"
cosmian_vm_client = { path = "../client" }
der = { workspace = true }
ecdsa = { workspace = true }
env_logger = "0.11"
futures = "0.3"
gethostname = "0.4"
hex = { workspace = true }
ima = { path = "../ima" }
num_cpus = "1.0"
p256 = { workspace = true }
pep440 = "0.2"
rand = { workspace = true }
rand_chacha = { workspace = true }
# Important: align the rustls version with actix rustls dependency
rustls = { version = "0.20", features = ["dangerous_configuration"] }
rustls-pemfile = "1.0"
serde = { workspace = true }
serde_json = { workspace = true }
sha1 = { workspace = true }
sha2 = { workspace = true }
spki = { workspace = true }
sysinfo = "0.29"
tokio = { version = "1.24.2", features = [
    "rt-multi-thread",
    "macros",
    "sync",
    "io-util",
] }
tokio-util = "0.7.4"
tee_attestation = { workspace = true }
thiserror = { workspace = true }
toml = "0.8"
tpm_quote = { workspace = true }
tracing = "0.1"
tss-esapi = "7.4.0"
uuid = { version = "1.3", features = ["serde", "v4"] }
walkdir = "2.4"
x509-cert = { workspace = true }
