---
# tasks file for ansible/roles/cosmian_vm_agent

- name: Check OS distribution
  ansible.builtin.debug:
    var: ansible_distribution

- name: Check Cosmian VM version
  ansible.builtin.debug:
    var: cosmian_vm_version

- name: Test using TPM2 Access Broker and Resource Manager
  when: ansible_distribution == 'Ubuntu'
  block:
    - name: Update packages cache
      ansible.builtin.apt:
        update_cache: true

    - name: Install TPM2 Access Broker and Resource Manager on Ubuntu
      ansible.builtin.apt:
        name:
          - tpm2-tools
          - tpm2-abrmd
        state: present
        update_cache: true

- name: Install TPM2 Access Broker and Resource Manager on RedHat
  when: ansible_distribution == 'RedHat'
  block:
    - name: Update packages cache
      ansible.builtin.dnf:
        update_cache: true

    - name: Install packages
      ansible.builtin.dnf:
        name:
          - tpm2-tools
          - tpm2-abrmd
          - cryptsetup
        state: present
        update_cache: true

- name: Check if tpm2-abrmd systemd service is enabled but stopped
  ansible.builtin.systemd_service:
    name: tpm2-abrmd
    enabled: true
    state: stopped
    daemon_reload: true

- name: Download Cosmian VM agent
  ansible.builtin.get_url:
    url: https://package.cosmian.com/cosmian_vm/{{ cosmian_vm_version }}/cosmian_vm_agent
    dest: /usr/sbin/
    mode: "0500"
    group: root
    owner: root

- name: Download Cosmian VM cert tool
  ansible.builtin.get_url:
    url: https://package.cosmian.com/cosmian_vm/{{ cosmian_vm_version }}/cosmian_certtool
    dest: /usr/sbin/
    mode: "0500"
    group: root
    owner: root

- name: Copy Cosmian VM filesystem tool
  ansible.builtin.copy:
    src: templates/cosmian_fstool
    dest: /usr/sbin/cosmian_fstool
    owner: root
    group: root
    mode: "0500"

- name: Create cosmian_vm directory in /etc
  ansible.builtin.file:
    path: /etc/cosmian_vm
    state: directory
    owner: root
    group: root
    mode: "0500"

- name: Copy agent.toml
  ansible.builtin.template:
    src: agent.toml.j2
    dest: /etc/cosmian_vm/agent.toml
    owner: root
    group: root
    mode: "0400"

- name: Create cosmian_vm directory in /var/lib
  ansible.builtin.file:
    path: /var/lib/cosmian_vm
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Mount a tmpfs volume
  ansible.posix.mount:
    src: tmpfs
    path: /var/lib/cosmian_vm/tmp
    opts: size=512m
    state: mounted
    fstype: tmpfs

- name: Add Mount LUKS script
  ansible.builtin.template:
    src: mount_luks.sh.j2
    dest: /root/mount_luks.sh
    owner: root
    group: root
    mode: "0700"
  tags: mount_luks_service

- name: Add Mount LUKS systemd service
  ansible.builtin.template:
    src: mount_luks.service.j2
    dest: /etc/systemd/system/mount_luks.service
    owner: root
    group: root
    mode: "0644"
  tags: mount_luks_service

- name: Check if Mount LUKS is enabled but stopped
  ansible.builtin.systemd_service:
    name: mount_luks
    enabled: true
    state: stopped
    daemon_reload: true
  tags: mount_luks_service

- name: Add Cosmian VM systemd service
  ansible.builtin.template:
    src: cosmian_vm_agent.service.j2
    dest: /etc/systemd/system/cosmian_vm_agent.service
    owner: root
    group: root
    mode: "0644"

- name: Check if Cosmian VM systemd service is enabled but stopped
  ansible.builtin.systemd_service:
    name: cosmian_vm_agent
    enabled: true
    state: stopped
    daemon_reload: true

- name: Open ports on RHEL
  when: ansible_distribution == 'RedHat'
  block:
    - name: Start firewalld service
      ansible.builtin.service:
        name: firewalld
        state: started

    - name: Open port 5555
      ansible.posix.firewalld:
        zone: public
        port: 5555/tcp
        permanent: true
        state: enabled

    - name: Always reload firewalld
      ansible.builtin.service:
        name: firewalld
        state: reloaded
