---
# tasks file for ansible/roles/cosmian_vm_agent

- name: Check OS distribution
  debug:
    var: ansible_distribution


- name: Copy cosmian_vm_agent
  ansible.builtin.copy:
    src: /tmp/cosmian_vm_agent/
    dest: /usr/sbin/
    remote_src: true
    owner: root
    group: root
    mode: 0500

- name: Change file ownership, group and permissions
  ansible.builtin.file:
    path: /usr/sbin/cosmian_vm_agent
    owner: root
    group: root
    mode: 0500

- name: Copy post-install.sh
  ansible.builtin.copy:
    src: /tmp/cosmian_vm_post_install.sh
    dest: /usr/sbin/cosmian_vm_post_install.sh
    remote_src: true
    owner: root
    group: root
    mode: 0500

- name: Create cosmian_vm directory 
  file:
    path: /etc/cosmian_vm
    state: directory
    owner: root
    group: root
    mode: 0500

- name: Copy agent.toml
  ansible.builtin.copy:
    src: /tmp/agent.toml
    dest: /etc/cosmian_vm/agent.toml
    remote_src: true
    owner: root
    group: root
    mode: 0500

- name: Create a mountable directory 
  file:
    path: /mnt/cosmian_vm/data
    state: directory
    owner: root
    group: root
    mode: 0500

- name: Mount a tmpfs volume
  ansible.posix.mount:
    src: tmpfs
    path: /mnt/cosmian_vm/data
    opts: "size=512m"
    state: mounted
    fstype: tmpfs

- name: Create cosmian agent log directory
  ansible.builtin.file:
    path: /var/log/cosmian_vm
    state: directory
    owner: root
    group: root
    mode: 0500

- name: Supervisor install on Ubuntu
  when: ansible_distribution == 'Ubuntu'
  block:
  - name: Update all packages to their latest version
    apt:
      update_cache: yes

  - name: Install Supervisor
    apt:
      name: supervisor
      state: latest
      update_cache: yes

  - name: Adding a program
    template:
      src: cosmian_vm_agent.conf.j2
      dest: /etc/supervisor/conf.d/cosmian_vm_agent.conf
      owner: root
      group: root
      mode: 0644

  - name: Check if Supervisor is started"
    systemd:
      name: supervisor
      state: started
    changed_when: false

- name: Supervisor install on RedHat
  when: ansible_distribution == 'RedHat' or ansible_distribution == 'CentOS' or ansible_distribution == 'Rocky'
  block:
  - name: Update all packages to their latest version
    dnf:
      update_cache: yes

  - name: Install supervisor
    ansible.builtin.dnf:
      name: supervisor
      state: latest
      update_cache: yes

  - name: Adding a program
    template:
      src: cosmian_vm_agent.conf.j2
      dest: /etc/supervisord.d/cosmian_vm_agent.ini
      owner: root
      group: root
      mode: 0644

  - name: Check if Supervisor is started
    systemd:
      name: supervisord
      enabled: true
      state: started
    changed_when: false

- name: Reread Supervisor conf file
  command: supervisorctl reread

- name: Update Supervisor process
  command: supervisorctl update
