---
on:
  workflow_call:
    inputs:
      product:
        required: true
        type: string
        default: cosmian-vm
      kms-version:
        required: true
        type: string
      ai-runner-version:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      product:
        description: Cosmian product
        required: true
        type: choice
        options:
          - cosmian-vm
          - kms
          - ai-runner
      kms-version:
        required: true
        type: string
        description: KMS server version
      ai-runner-version:
        required: true
        type: string
        description: AI Runner version

concurrency:
  group: marketplace_aws

name: AWS images

jobs:
  clean-resources:
    uses: ./.github/workflows/aws_clean.yml
    secrets: inherit

  sev-image:
    strategy:
      fail-fast: false
      matrix:
        distrib: [ubuntu, rhel]
        product:
          - ${{ inputs.product }}
    name: (AWS) ${{ matrix.product }} - ${{ matrix.distrib }} - SEV
    needs:
      - clean-resources
    secrets: inherit
    uses: ./.github/workflows/aws_ansible.yml
    with:
      techno: sev
      distrib: ${{ matrix.distrib }}
      product: ${{ matrix.product }}
      kms-version: ${{ inputs.kms-version }}
      ai-runner-version: ${{ inputs.ai-runner-version }}

  post-clean-resources:
    if: success() || cancelled()
    needs:
      - sev-image
    uses: ./.github/workflows/aws_clean.yml
    secrets: inherit
