---
name: Build and test image for AWS SEV

on:
  workflow_call:
    inputs:
      distrib:
        required: true
        type: string
      techno:
        required: true
        type: string
      product:
        required: true
        type: string
      kms-version:
        required: true
        type: string
      machine-type:
        required: true
        type: string
      ai-runner-version:
        required: true
        type: string

env:
  AWS_REGION: eu-west-1

jobs:
  build-image:
    name: Packer build - ${{ inputs.distrib }} - ${{ inputs.techno }} - ${{ inputs.product }}
    if: contains(inputs.product, 'ai-runner') != true || contains(inputs.distrib, 'rhel') != true
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      id-token: write
    defaults:
      run:
        working-directory: ./packer
    outputs:
      timestamp: ${{ steps.env.outputs.TIMESTAMP }}
      image_name: ${{ steps.env.outputs.IMAGE_NAME }}
      ci_instance: ${{ steps.env.outputs.CI_INSTANCE }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create env variables
        id: env
        run: |
          TIMESTAMP="$(date -u +'%Y%m%d%H%M%S')"
          echo "TIMESTAMP=$TIMESTAMP" >> "$GITHUB_OUTPUT"
          echo "IMAGE_NAME=temp-$TIMESTAMP-${{ inputs.product }}-${{ inputs.distrib }}-${{ inputs.techno }}" >> "$GITHUB_OUTPUT"
          echo "CI_INSTANCE=gh-ci-$TIMESTAMP-${{ inputs.product }}-${{ inputs.distrib }}-${{ inputs.techno }}" >> "$GITHUB_OUTPUT"

      - name: Setup packer
        uses: hashicorp/setup-packer@main

      - name: Install packer plugins
        run: |
          packer plugins install github.com/hashicorp/amazon
          packer plugins install github.com/hashicorp/ansible

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      - name: Packer build image
        env:
          TIMESTAMP: ${{ steps.env.outputs.TIMESTAMP }}
          IMAGE_NAME: ${{ steps.env.outputs.IMAGE_NAME }}
          KMS_VERSION: ${{ inputs.kms-version }}
          AI_RUNNER_VERSION: ${{ inputs.ai-runner-version }}
        run: |
          set -ex
          if [[ ${GITHUB_REF} = *'refs/tags/'* ]]; then
            export COSMIAN_VM_VERSION="${{ github.ref_name }}"
          else
            export COSMIAN_VM_VERSION="last_build/${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}"
          fi

          if [ "${{ inputs.distrib }}" = "ubuntu" ]; then
            export AMI="ami-078b6cc5ff646a9ec"
          else
            export AMI="ami-0a410cf86963e05ef"
          fi
          bash ../.github/scripts/aws-packer-build.sh "${{ inputs.product }}" "${{ inputs.distrib }}" "$AMI"

  test-image:
    name: Test image - ${{ inputs.distrib }} - ${{ inputs.techno }} - ${{ inputs.product }}
    if: contains(inputs.product, 'ai-runner') != true || contains(inputs.distrib, 'rhel') != true
    runs-on: ubuntu-22.04
    needs: build-image
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      - name: Launch AWS instance
        id: run-aws-instance
        env:
          IMAGE_NAME: ${{ needs.build-image.outputs.image_name }}
          CI_INSTANCE: ${{ needs.build-image.outputs.ci_instance }}
        run: |
          set -ex

          IMAGE_TO_INSTANTIATE=$(aws ec2 describe-images --filters "Name=name,Values=$IMAGE_NAME" --query 'Images[].ImageId' --output text)

          aws ec2 create-security-group --group-name ${CI_INSTANCE}-ci-sg --description "Security group for image test"
          aws ec2 authorize-security-group-ingress --group-name ${CI_INSTANCE}-ci-sg --protocol tcp --port 22 --cidr 0.0.0.0/0
          aws ec2 authorize-security-group-ingress --group-name ${CI_INSTANCE}-ci-sg --protocol tcp --port 5555 --cidr 0.0.0.0/0
          if [ "${{ inputs.product }}" = "kms" ]; then
            aws ec2 authorize-security-group-ingress --group-name ${CI_INSTANCE}-ci-sg --protocol tcp --port 443 --cidr 0.0.0.0/0
          elif [ "${{ inputs.product }}" = "ai-runner" ]; then
            aws ec2 authorize-security-group-ingress --group-name ${CI_INSTANCE}-ci-sg --protocol tcp --port 443 --cidr 0.0.0.0/0
          fi

          AMI=$(aws ec2 run-instances \
            --tag-specifications "ResourceType=instance,Tags=[{Key=Name,Value=$CI_INSTANCE}]" \
            --image-id ${IMAGE_TO_INSTANTIATE} \
            --instance-type ${{ inputs.machine-type }} \
            --cpu-options AmdSevSnp=enabled \
            --block-device-mappings "DeviceName=/dev/sda1,Ebs={VolumeType=gp3,VolumeSize=20}" \
            --security-groups ${CI_INSTANCE}-ci-sg \
            --query 'Instances[0].InstanceId' --output text)

          IP_ADDR=$(aws ec2 describe-instances --filters "Name=tag:Name,Values=${CI_INSTANCE}" --query 'Reservations[*].Instances[*].PublicIpAddress' --output text)
          echo "IP_ADDR=${IP_ADDR}" >> "$GITHUB_OUTPUT"

          # Wait for VM to be ready
          aws ec2 wait instance-running --instance-ids $AMI
          timeout 40m bash -c "until nc -z $IP_ADDR 5555; do sleep 10; done"

      - name: Download Cosmian VM CLI
        run: |
          set -e
          if [[ ${GITHUB_REF} = *'refs/tags/'* ]]; then
            COSMIAN_VM_VERSION="${{ github.ref_name }}"
          else
            COSMIAN_VM_VERSION="last_build/${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}"
          fi
          wget https://package.cosmian.com/cosmian_vm/$COSMIAN_VM_VERSION/cosmian_vm
          chmod +x ./cosmian_vm

      - name: Test Cosmian VM Agent on AWS instance
        id: test_cosmian_vm
        env:
          CI_INSTANCE: ${{ needs.build-image.outputs.ci_instance }}
          IP_ADDR: ${{ steps.run-aws-instance.outputs.IP_ADDR }}
        run: |
          set -ex
          bash .github/scripts/aws-${{ inputs.product }}-tests.sh "$CI_INSTANCE" "$IP_ADDR" "$AWS_REGION"

      - name: Terminate AWS instance
        if: success() || failure() || cancelled()
        env:
          IMAGE_NAME: ${{ needs.build-image.outputs.image_name }}
          CI_INSTANCE: ${{ needs.build-image.outputs.ci_instance }}
        run: |
          set -x
          set +e
          export CI_INSTANCE_ID=$(aws ec2 describe-instances --filters "Name=tag:Name,Values=${CI_INSTANCE}" --query 'Reservations[].Instances[].[InstanceId]' --output text)

          aws ec2 terminate-instances --instance-ids $CI_INSTANCE_ID

      - name: Delete AWS image
        if: (success() || failure() || cancelled()) && startsWith(github.ref, 'refs/tags') != true
        env:
          IMAGE_NAME: ${{ needs.build-image.outputs.image_name }}
          CI_INSTANCE: ${{ needs.build-image.outputs.ci_instance }}
        run: |
          set -x
          set +e
          export IMAGE_TO_DELETE=$(aws ec2 describe-images --filters "Name=name,Values=$IMAGE_NAME" --query 'Images[].ImageId' --output text)
          export SNAPSHOT_ID=$(aws ec2 describe-images --filters "Name=name,Values=$IMAGE_NAME" --query 'Images[].BlockDeviceMappings[].Ebs[].SnapshotId[]' --output text)

          aws ec2 deregister-image --image-id $IMAGE_TO_DELETE
          aws ec2 delete-snapshot --snapshot-id $SNAPSHOT_ID

  release-image:
    name: Release image - ${{ inputs.distrib }} - ${{ inputs.techno }} - ${{ inputs.product }}
    if: (contains(inputs.product, 'ai-runner') != true || contains(inputs.distrib, 'rhel') != true) && startsWith(github.ref, 'refs/tags')
    runs-on: ubuntu-22.04
    needs: [build-image, test-image]
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      - name: Copy image to public project
        env:
          CI_INSTANCE: ${{ needs.build-image.outputs.ci_instance }}
          IMAGE_NAME: ${{ needs.build-image.outputs.image_name }}
          TAG: ${{ github.ref_name }}
          KMS: ${{ inputs.kms-version }}
          AI_RUNNER: ${{ inputs.ai-runner-version }}
        run: |
          set -ex

          VERSION=$(echo $TAG | sed 's/\./-/g; s/_/-/g; s/+/-/g')
          KMS_VERSION=$(echo $KMS | sed 's/\./-/g; s/_/-/g; s/+/-/g')
          AI_RUNNER_VERSION=$(echo $AI_RUNNER | sed 's/\./-/g; s/_/-/g; s/+/-/g')

          if [ "${{ inputs.product }}" = "cosmian-vm" ]; then
            NEW_IMAGE_NAME=cosmian-vm-$VERSION-${{ inputs.techno }}-${{ inputs.distrib }}
          elif [ "${{ inputs.product }}" = "ai-runner" ]; then
            NEW_IMAGE_NAME=cosmian-vm-${VERSION}-ai-runner-${AI_RUNNER_VERSION}-${{ inputs.techno }}-${{ inputs.distrib }}
          else
            NEW_IMAGE_NAME=cosmian-vm-${VERSION}-kms-${KMS_VERSION}-${{ inputs.techno }}-${{ inputs.distrib }}
          fi

          AMI=$(aws ec2 describe-images --filters "Name=name,Values=$IMAGE_NAME" --query 'Images[].ImageId' --output text)

          aws ec2 copy-image \
            --name $NEW_IMAGE_NAME \
            --source-region eu-west-1 \
            --source-image-id ${AMI}
