---
on:
  workflow_call:
  workflow_dispatch:

concurrency:
  group: marketplace_aws

name: AWS images build

jobs:
  clean-resources:
    uses: ./.github/workflows/aws_clean.yml
    secrets: inherit

  sev-image:
    strategy:
      fail-fast: false
      matrix:
        distrib: [ubuntu]
        product: [cosmian-vm]
    name: (AWS) ${{ matrix.product }} - ${{ matrix.distrib }} - SEV
    needs:
      - clean-resources
    secrets: inherit
    uses: ./.github/workflows/aws_image.yml
    with:
      techno: sev
      distrib: ${{ matrix.distrib }}
      product: ${{ matrix.product }}
      kms-version: 4.16.0
      ai-runner-version: 0.3.0
      base-version: 0.1.5

  post-clean-resources:
    if: success() || cancelled()
    needs:
      - sev-image
    uses: ./.github/workflows/aws_clean.yml
    secrets: inherit
