---
on:
  workflow_call:

concurrency:
  group: marketplace_aws

name: AWS images build

jobs:
  clean-aws-resources:
    uses: ./.github/workflows/aws_clean.yml
    secrets: inherit

  build-test-aws-sev-image:
    strategy:
      fail-fast: false
      matrix:
        distrib: [ubuntu, rhel]
        product: [cosmian-vm, kms]
    name: (AWS) ${{ matrix.product }} - ${{ matrix.distrib }} - SEV
    needs:
      - clean-aws-resources
    secrets: inherit
    uses: ./.github/workflows/aws_image.yml
    with:
      techno: sev
      distrib: ${{ matrix.distrib }}
      product: ${{ matrix.product }}
      kms-version: 4.16.0
      machine-type: c6a.large

  post-clean-aws-resources:
    needs: build-test-aws-sev-image
    uses: ./.github/workflows/aws_clean.yml
    secrets: inherit
