---
on:
  workflow_call:
  workflow_dispatch:

concurrency:
  group: marketplace_azure

name: Azure images build

jobs:
  clean-resources:
    uses: ./.github/workflows/azure_clean.yml
    secrets: inherit

  sev-image:
    strategy:
      fail-fast: false
      matrix:
        distrib: [ubuntu]
        # product: [cosmian-vm]
        product: [ai-runner]
    name: (AZURE) ${{ matrix.product }} - ${{ matrix.distrib }} - SEV
    needs:
      - clean-resources
    secrets: inherit
    uses: ./.github/workflows/azure_image.yml
    with:
      techno: sev
      distrib: ${{ matrix.distrib }}
      product: ${{ matrix.product }}
      kms-version: 4.16.0
      ai-runner-version: 0.3.0

  # To be removed
  tdx-image:
    strategy:
      fail-fast: false
      matrix:
        distrib: [ubuntu]
        product: [ai-runner]
    name: (AZURE) ${{ matrix.product }} - ${{ matrix.distrib }} - TDX
    needs:
      - clean-resources
    secrets: inherit
    uses: ./.github/workflows/azure_image.yml
    with:
      techno: tdx
      distrib: ${{ matrix.distrib }}
      product: ${{ matrix.product }}
      kms-version: 4.16.0
      ai-runner-version: 0.3.0
  # To be removed

  post-clean-resources:
    if: success() || failure() || cancelled()
    needs:
      - sev-image
    uses: ./.github/workflows/azure_clean.yml
    secrets: inherit
