---
on:
  workflow_call:
  workflow_dispatch:

concurrency:
  group: marketplace_azure

name: Azure base images build

jobs:
  image:
    strategy:
      fail-fast: false
      matrix:
        distrib: [rhel]
        product: [base-image]
        techno: [sev]
        exclude:
          - techno: tdx
            distrib: rhel
    name: (AZURE) ${{ matrix.product }} - ${{ matrix.distrib }} - ${{ matrix.techno }}
    secrets: inherit
    uses: ./.github/workflows/azure_base_image.yml
    with:
      techno: ${{ matrix.techno }}
      distrib: ${{ matrix.distrib }}
      product: ${{ matrix.product }}
      base-version: 0.0.3
