---
on:
  workflow_call:
    inputs:
      base-version:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      base-version:
        required: true
        type: string
        description: Cosmian Base Image version
concurrency:
  group: marketplace_aws

name: AWS base images build

jobs:
  sev-base-image:
    strategy:
      fail-fast: false
      matrix:
        distrib: [ubuntu, rhel]
        product: [base-image]
    name: (AWS) ${{ matrix.product }} - ${{ matrix.distrib }} - SEV
    secrets: inherit
    uses: ./.github/workflows/base_aws_image.yml
    with:
      techno: sev
      distrib: ${{ matrix.distrib }}
      product: ${{ matrix.product }}
      base-version: ${{ inputs.base-version }}
