---
on:
  workflow_call:
    inputs:
      base-version:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      base-version:
        required: true
        type: string
        description: Cosmian Base Image version

concurrency:
  group: marketplace_azure

name: Base images Azure

jobs:
  image:
    strategy:
      fail-fast: false
      matrix:
        distrib: [ubuntu, rhel]
        product: [base-image]
        techno: [sev, tdx]
        exclude:
          - techno: tdx
            distrib: rhel
    name: (AZURE) ${{ matrix.product }} - ${{ matrix.distrib }} - ${{ matrix.techno }}
    secrets: inherit
    uses: ./.github/workflows/azure_packer_build.yml
    with:
      techno: ${{ matrix.techno }}
      distrib: ${{ matrix.distrib }}
      product: ${{ matrix.product }}
      base-version: ${{ inputs.base-version }}
      kms-version: 0.0.0
      ai-runner-version: 0.0.0
