---
name: Manual base images recreation

on:
  workflow_dispatch:

jobs:
  azure:
    uses: ./.github/workflows/base_azure_main.yml
    with:
      base-version: 0.1.11
    secrets: inherit

  gcp:
    uses: ./.github/workflows/base_gcp_main.yml
    with:
      base-version: 0.1.11
    secrets: inherit

  aws:
    uses: ./.github/workflows/base_aws_main.yml
    with:
      base-version: 0.1.11
    secrets: inherit
