name: Cargo build and Publish VM Image

on:
  workflow_call:

jobs:
  build-cosmian-vm:
    name: Build Cosmian VM Agent
    runs-on: [self-hosted, no-tee]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: geekyeggo/delete-artifact@v2
        with:
          name: cosmian_vm

      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y libtss2-dev

      - uses: actions/cache@v3
        id: cargo_cache
        continue-on-error: false
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-build-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-build-${{ hashFiles('**/Cargo.lock') }}

      - uses: dtolnay/rust-toolchain@stable
        if: steps.cargo_cache.outputs.cache-hit != 'true'
        with:
          toolchain: stable
          components: rustfmt, clippy

      - name: Build Cosmian VM binaries
        if: steps.cargo_cache.outputs.cache-hit != 'true'
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release

      - name: Upload artifacts
        if: steps.cargo_cache.outputs.cache-hit != 'true'
        uses: actions/upload-artifact@v3
        with:
          name: cosmian_vm
          path: |
            target/release/cosmian_vm_agent
            target/release/cosmian_vm
            target/release/cosmian_certtool
            target/release/cosmian_fstool
          retention-days: 1
          if-no-files-found: error

      - name: Release on tags, attach asset on release
        if: startsWith(github.ref, 'refs/tags/') && steps.cargo_cache.outputs.cache-hit != 'true'
        uses: softprops/action-gh-release@v1
        with:
          files: |
            target/release/cosmian_vm_agent
            target/release/cosmian_vm
            target/release/cosmian_certtool
            resources/scripts/cosmian_fstool

      - name: Push to package.cosmian.com
        if: steps.cargo_cache.outputs.cache-hit != 'true'
        run: |
          set -x
          DESTINATION_DIR=/mnt/package/cosmian_vm/last_build/$VERSION
          ssh cosmian@package.cosmian.com mkdir -p $DESTINATION_DIR
          scp target/release/cosmian_vm_agent target/release/cosmian_vm target/release/cosmian_certtool resources/scripts/cosmian_fstool cosmian@package.cosmian.com:$DESTINATION_DIR/
        env:
          VERSION: ${{ github.head_ref }}

      - name: Push to package.cosmian.com - tags
        if: startsWith(github.ref, 'refs/tags/') && steps.cargo_cache.outputs.cache-hit != 'true'
        run: |
          set -x
          DESTINATION_DIR=/mnt/package/cosmian_vm/$VERSION
          ssh cosmian@package.cosmian.com mkdir -p $DESTINATION_DIR
          scp target/release/cosmian_vm_agent target/release/cosmian_vm target/release/cosmian_certtool cosmian@package.cosmian.com:$DESTINATION_DIR/
        env:
          VERSION: ${{ github.ref_name }}
