name: Build and Publish VM Image

on:
  # Only run when pull request is closed and merged into main
  pull_request:
    branches:
      - main
    types:
      - closed
  # Do not run on push except on tags
  push:
    branches-ignore:
      - "**"
    tags:
      - "**"

jobs:
  build-cosmian-vm:
    name: Build Cosmian VM Agent
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Build the agent
        run: cargo build

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: cosmian_vm_agent
          path: target/debug/cosmian_vm_agent

  packer-docker-base:
    needs: build-cosmian-vm
    name: Build Cosmian VM Image
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: ./packer

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: cosmian_vm_agent
          path: packer/cosmian_vm_agent

      - name: "Authenticate to Google Cloud"
        id: "auth"
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: "${{ secrets.GOOGLE_CREDENTIALS }}"

      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        id: setup

      - name: Run `packer init`
        id: init
        run: packer init -machine-readable gcp.pkr.hcl

      - name: Install Googlecompute plugin
        run: |
          packer plugins install github.com/hashicorp/googlecompute
          packer plugins install github.com/hashicorp/ansible

      - name: Run `packer build`
        id: build
        run: packer build gcp.pkr.hcl
