on:
  # Run on push except on tags
  push:
    branches:
      - "**"
    tags-ignore:
      - "**"

name: CI

jobs:

  check:
    name: Rust Check
    runs-on: ubuntu-22.04

    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y tpm2-tools libtss2-dev

      - name: Checkout
        uses: actions/checkout@v4

      - name: Cargo cache
        uses: actions/cache@v4
        id: cargo-cache
        continue-on-error: false
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
          key: ${{ runner.os }}-check-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Install Rust toolchain and components
        uses: dtolnay/rust-toolchain@stable
        if: steps.cargo-cache.outputs.cache-hit != 'true'
        with:
          toolchain: stable
          components: rustfmt, clippy

      - name: Cargo install cargo-machete
        if: steps.cargo-cache.outputs.cache-hit != 'true'
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: cargo-machete

      - name: Cargo fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

      - name: Cargo check
        uses: actions-rs/cargo@v1
        with:
          command: check

      - name: Clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings

      - name: Machete (deps checker)
        uses: actions-rs/cargo@v1
        with:
          command: machete

  test:
    name: Rust Test
    runs-on: ubuntu-22.04
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y tpm2-tools libtss2-dev

      - name: Checkout
        uses: actions/checkout@v4

      - name: Cargo cache
        uses: actions/cache@v4
        id: cargo-cache
        continue-on-error: false
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
          key: ${{ runner.os }}-test-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Install Rust toolchain and components
        uses: dtolnay/rust-toolchain@stable
        if: steps.cargo-cache.outputs.cache-hit != 'true'
        with:
          toolchain: stable
          components: rustfmt, clippy

      - name: Cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test

  build:
    name: Rust Build
    runs-on: ubuntu-22.04

    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y tpm2-tools libtss2-dev

      - name: Checkout
        uses: actions/checkout@v4

      - name: Cargo cache
        uses: actions/cache@v4
        id: cargo-cache
        continue-on-error: false
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
          key: ${{ runner.os }}-build-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Install Rust toolchain and components
        uses: dtolnay/rust-toolchain@stable
        if: steps.cargo-cache.outputs.cache-hit != 'true'
        with:
          toolchain: stable
          components: rustfmt, clippy

      - name: Cargo build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: cosmian_vm
          path: |
            target/release/cosmian_vm_agent
            target/release/cosmian_vm
            target/release/cosmian_certtool
            resources/scripts/cosmian_fstool
          retention-days: 1
          if-no-files-found: error

  audit:
    name: Rust Audit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cargo cache
        uses: actions/cache@v4
        id: cargo-cache
        continue-on-error: false
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
          key: ${{ runner.os }}-audit-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        if: steps.cargo-cache.outputs.cache-hit != 'true'

      - name: Cargo audit
        uses: rustsec/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  build-test-gcp-image:
    strategy:
      matrix:
        distrib: [ubuntu, rhel]
    name: GCP image (${{ matrix.distrib }})
    needs: [check, build, test, audit]
    secrets: inherit
    uses: ./.github/workflows/gcp_image.yml
    with:
      distrib: ${{ matrix.distrib }}

  release:
    name: Release
    needs: [build-test-gcp-image]
    secrets: inherit
    uses: ./.github/workflows/release.yml
