# alias runner-sgx="ssh cosmian@162.19.87.37" # OVH
# alias runner-sev="ssh cosmian@34.90.22.143" # GCP
# alias runner-tdx="ssh cosmian@34.70.122.49" # GCP

on:
  # Run on push except on tags
  push:
    branches:
      - "**"
    tags-ignore:
      - "**"

name: Rust compilation, check and test

jobs:
  build-cosmian-vm:
    uses: ./.github/workflows/cargo_build.yml

  test-cosmian-vm:
    needs: build-cosmian-vm
    uses: ./.github/workflows/agent.yml

  check:
    name: Check
    runs-on: ubuntu-22.04

    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y tpm2-tools libtss2-dev

      - uses: actions/checkout@v2

      - uses: actions/cache@v3
        id: cargo_cache
        continue-on-error: false
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-lint-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-lint-${{ hashFiles('**/Cargo.lock') }}

      - uses: dtolnay/rust-toolchain@stable
        if: steps.cargo_cache.outputs.cache-hit != 'true'
        with:
          toolchain: stable
          components: rustfmt, clippy

      - name: Cargo install cargo-machete
        if: steps.cargo_cache.outputs.cache-hit != 'true'
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: cargo-machete

      - name: Cargo fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

      - name: Cargo check
        uses: actions-rs/cargo@v1
        with:
          command: check

      - name: Clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings

      - name: Machete (deps checker)
        uses: actions-rs/cargo@v1
        with:
          command: machete

      - name: Cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test

  cargo-audit:
    name: Security Audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        id: cargo_cache
        continue-on-error: false
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-audit-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-audit-${{ hashFiles('**/Cargo.lock') }}

      - uses: dtolnay/rust-toolchain@stable
        if: steps.cargo_cache.outputs.cache-hit != 'true'

      - uses: rustsec/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
