---
on:
  # Run on push except on tags
  push:
    branches:
      - '**'
    tags:
      - '**'

name: CI

jobs:
  build-cosmian-vm-binaries:
    uses: ./.github/workflows/build.yml

  build-test-gcp-sev-image:
    strategy:
      fail-fast: false
      matrix:
        distrib: [ubuntu]
        product: [cosmian-vm, kms]
    name: (${{ matrix.distrib }}) -> GCP SEV image
    needs: build-cosmian-vm-binaries
    secrets: inherit
    uses: ./.github/workflows/gcp_image.yml
    with:
      techno: sev
      distrib: ${{ matrix.distrib }}
      machine-type: n2d-standard-2
      zone: europe-west4-a
      confidential-compute-type: SEV_SNP
      min-cpu-platform: AMD Milan
      project: cosmian-dev
      mode: beta
      maintenance: maintenance-policy=TERMINATE
      product: ${{ matrix.product }}

  release:
    name: Release
    needs: [build-test-gcp-sev-image]
    secrets: inherit
    uses: ./.github/workflows/release.yml
