---
name: Build and test image for GCP SEV and TDX

on:
  workflow_call:
    inputs:
      distrib:
        required: true
        type: string
      machine-type:
        required: true
        type: string
      zone:
        required: true
        type: string
      confidential-compute-type:
        required: true
        type: string
      techno:
        required: true
        type: string
      min-cpu-platform:
        required: true
        type: string
      mode:
        required: true
        type: string
      product:
        required: true
        type: string
      kms-version:
        required: true
        type: string

env:
  GCP_DEV_PROJECT: cosmian-dev
  GCP_PUBLIC_PROJECT: cosmian-public

jobs:
  build-image:
    name: Packer build - ${{ inputs.distrib }} - ${{ inputs.techno }} - ${{ inputs.product }}
    if: startsWith(github.ref, 'refs/tags/') || contains(inputs.product, 'cosmian-vm')
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      id-token: write
    defaults:
      run:
        working-directory: ./packer
    outputs:
      timestamp: ${{ steps.env.outputs.TIMESTAMP }}
      image_name: ${{ steps.env.outputs.IMAGE_NAME }}
      ci_instance: ${{ steps.env.outputs.CI_INSTANCE }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create env variables
        id: env
        run: |
          TIMESTAMP="$(date -u +'%Y%m%d%H%M%S')"
          echo "TIMESTAMP=$TIMESTAMP" >> "$GITHUB_OUTPUT"
          echo "IMAGE_NAME=temp-$TIMESTAMP-${{ inputs.product }}-${{ inputs.distrib }}-${{ inputs.techno }}" >> "$GITHUB_OUTPUT"
          echo "CI_INSTANCE=gh-ci-$TIMESTAMP-${{ inputs.product }}-${{ inputs.distrib }}-${{ inputs.techno }}" >> "$GITHUB_OUTPUT"

      - name: Setup packer
        uses: hashicorp/setup-packer@main

      - name: Install packer plugins
        run: |
          packer plugins install github.com/hashicorp/googlecompute
          packer plugins install github.com/hashicorp/ansible

      - name: GCP auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GOOGLE_COSMIAN_DEV_CREDENTIALS }}

      - name: Packer build image
        if: startsWith(github.ref, 'refs/tags/') != true
        env:
          TIMESTAMP: ${{ steps.env.outputs.TIMESTAMP }}
          IMAGE_NAME: ${{ steps.env.outputs.IMAGE_NAME }}
          KMS_VERSION: ${{ inputs.kms-version }}
          TECHNO: ${{ inputs.techno }}
        run: |
          set -ex
          COSMIAN_VM_VERSION="last_build/${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}"
          bash ../.github/scripts/gcp-packer-build.sh "${{ inputs.product }}" "${{ inputs.distrib }}" "$COSMIAN_VM_VERSION"

      - name: Packer build image
        if: startsWith(github.ref, 'refs/tags/')
        env:
          TIMESTAMP: ${{ steps.env.outputs.TIMESTAMP }}
          IMAGE_NAME: ${{ steps.env.outputs.IMAGE_NAME }}
          VERSION: ${{ github.ref_name }}
          KMS_VERSION: ${{ inputs.kms-version }}
          TECHNO: ${{ inputs.techno }}
        run: |
          set -ex
          COSMIAN_VM_VERSION="$VERSION"
          bash ../.github/scripts/gcp-packer-build.sh "${{ inputs.product }}" "${{ inputs.distrib }}" "$COSMIAN_VM_VERSION"

  test-image:
    name: Test image - ${{ inputs.distrib }} - ${{ inputs.techno }} - ${{ inputs.product }}
    runs-on: ubuntu-22.04
    if: startsWith(github.ref, 'refs/tags/') || contains(inputs.product, 'cosmian-vm')
    needs: build-image
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: GCP auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GOOGLE_COSMIAN_DEV_CREDENTIALS }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          version: latest
          install_components: ${{ inputs.mode }}

      - name: Launch GCP instance
        id: run-gcp-instance
        env:
          IMAGE_NAME: ${{ needs.build-image.outputs.image_name }}
          CI_INSTANCE: ${{ needs.build-image.outputs.ci_instance }}
        run: |
          set -ex
          gcloud ${{ inputs.mode }} compute instances create $CI_INSTANCE \
            --machine-type ${{ inputs.machine-type }} \
            --zone ${{ inputs.zone }} \
            --min-cpu-platform="${{ inputs.min-cpu-platform }}" \
            --confidential-compute-type=${{ inputs.confidential-compute-type }} \
            --shielded-secure-boot \
            --image="$IMAGE_NAME" \
            --image-project=$GCP_DEV_PROJECT \
            --project $GCP_DEV_PROJECT \
            --tags $CI_INSTANCE-fw \
            --maintenance-policy=TERMINATE \
            --max-run-duration=20m \
            --instance-termination-action=DELETE
          IP_ADDR=$(gcloud ${{ inputs.mode }} compute instances describe $CI_INSTANCE --format='get(networkInterfaces[0].accessConfigs[0].natIP)' --zone=${{ inputs.zone }})
          echo "IP_ADDR=${IP_ADDR}" >> "$GITHUB_OUTPUT"

      - name: Create Firewall Rules for CLI Ports
        env:
          CI_INSTANCE: ${{ needs.build-image.outputs.ci_instance }}
        run: |
          if [ "${{ inputs.product }}" = "cosmian-vm" ]; then
            gcloud compute firewall-rules create ${CI_INSTANCE}-allow-ports-cli \
              --network=default \
              --allow=tcp:5555 \
              --target-tags=$CI_INSTANCE-fw
          else
            gcloud compute firewall-rules create ${CI_INSTANCE}-allow-ports-cli \
              --network=default \
              --allow=tcp:80,tcp:443,tcp:5555,tcp:8080 \
              --target-tags=$CI_INSTANCE-fw
          fi

      - name: Download Cosmian VM CLI
        if: startsWith(github.ref, 'refs/tags/') != true
        run: |
          export BRANCH=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}
          wget https://package.cosmian.com/cosmian_vm/last_build/$BRANCH/cosmian_vm

      - name: Download Cosmian VM CLI
        if: startsWith(github.ref, 'refs/tags/')
        env:
          VERSION: ${{ github.ref_name }}
        run: |
          wget https://package.cosmian.com/cosmian_vm/$VERSION/cosmian_vm

      - name: Change permissions of binaries
        run: |
          set -e
          chmod +x ./cosmian_vm

      - name: Test Cosmian VM Agent on GCP instance
        id: test_cosmian_vm
        env:
          CI_INSTANCE: ${{ needs.build-image.outputs.ci_instance }}
          IP_ADDR: ${{ steps.run-gcp-instance.outputs.IP_ADDR }}
        run: |
          set -ex
          bash .github/scripts/gcp-${{ inputs.product }}-tests.sh "${{ inputs.mode }}" "$CI_INSTANCE" "${{ inputs.zone }}" "$IP_ADDR"

      - name: Stop and delete GCP instance
        if: success() || failure() || cancelled()
        env:
          CI_INSTANCE: ${{ needs.build-image.outputs.ci_instance }}
        run: |
          set +e
          gcloud ${{ inputs.mode }} compute instances delete --quiet $CI_INSTANCE --zone ${{ inputs.zone }} --project $GCP_DEV_PROJECT
          gcloud compute firewall-rules delete ${CI_INSTANCE}-allow-ports-cli --quiet
          set -e

      - name: Delete GCP CI image
        if: startsWith(github.ref, 'refs/tags') != true || failure() || cancelled()
        env:
          IMAGE_NAME: ${{ needs.build-image.outputs.image_name }}
        run: |
          gcloud ${{ inputs.mode }} compute images delete --quiet $IMAGE_NAME

  test-ansible:
    name: Test Ansible - ${{ inputs.distrib }} - ${{ inputs.techno }} - ${{ inputs.product }}
    if: startsWith(github.ref, 'refs/tags/') != true && contains(inputs.product, 'cosmian-vm')
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Create env variables
        id: env
        run: |
          TIMESTAMP="$(date -u +'%Y%m%d%H%M%S')"
          echo "TIMESTAMP=$TIMESTAMP" >> "$GITHUB_OUTPUT"
          echo "CI_INSTANCE=gh-ci-a-$TIMESTAMP-${{ inputs.product }}-${{ inputs.distrib }}-${{ inputs.techno }}" >> "$GITHUB_OUTPUT"

      - name: Checkout
        uses: actions/checkout@v4

      - name: GCP auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GOOGLE_COSMIAN_DEV_CREDENTIALS }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          version: latest
          install_components: ${{ inputs.mode }}

      - name: Launch GCP instance
        id: run-gcp-instance
        env:
          CI_INSTANCE: ${{ steps.env.outputs.ci_instance }}
        run: |
          set -ex

          if [ "${{ inputs.distrib }}" = "ubuntu" ]; then
            IMAGE_OPTIONS="--image-project=ubuntu-os-cloud --project $GCP_DEV_PROJECT"
            if [ "${{ inputs.techno }}" = "sev" ]; then
              IMAGE_NAME="ubuntu-2204-jammy-v20240501"
            else
              IMAGE_NAME="ubuntu-2204-tdx-v20240220"
              IMAGE_OPTIONS=""
            fi
          else
            IMAGE_OPTIONS="--image-project=rhel-cloud --project $GCP_DEV_PROJECT"
            IMAGE_NAME="rhel-9-v20240415"
          fi

          ssh-keygen -t rsa -b 4096 -C "$CI_INSTANCE@example.com" -f $HOME/.ssh/id_rsa -q -N ""
          PUBKEY=$(cat $HOME/.ssh/id_rsa.pub)

          gcloud ${{ inputs.mode }} compute instances create $CI_INSTANCE \
            --machine-type ${{ inputs.machine-type }} \
            --zone ${{ inputs.zone }} \
            --min-cpu-platform="${{ inputs.min-cpu-platform }}" \
            --confidential-compute-type=${{ inputs.confidential-compute-type }} \
            --shielded-secure-boot \
            --image="$IMAGE_NAME" \
            $IMAGE_OPTIONS \
            --tags $CI_INSTANCE-fw \
            --maintenance-policy=TERMINATE \
            --max-run-duration=30m \
            --instance-termination-action=DELETE \
            --metadata=ssh-keys="cosmian:$PUBKEY"
          IP_ADDR=$(gcloud ${{ inputs.mode }} compute instances describe $CI_INSTANCE --format='get(networkInterfaces[0].accessConfigs[0].natIP)' --zone=${{ inputs.zone }})
          echo "IP_ADDR=${IP_ADDR}" >> "$GITHUB_OUTPUT"

          # Wait for VM to be ready
          sleep 60

      - name: Create Firewall Rules for CLI Ports
        env:
          CI_INSTANCE: ${{ steps.env.outputs.ci_instance }}
        run: |
          if [ "${{ inputs.product }}" = "cosmian-vm" ]; then
            gcloud compute firewall-rules create ${CI_INSTANCE}-allow-ports-cli \
              --network=default \
              --allow=tcp:22,tcp:5555 \
              --target-tags=$CI_INSTANCE-fw
          else
            gcloud compute firewall-rules create ${CI_INSTANCE}-allow-ports-cli \
              --network=default \
              --allow=tcp:22,tcp:80,tcp:443,tcp:5555,tcp:8080 \
              --target-tags=$CI_INSTANCE-fw
          fi

      - name: Ansible installation
        env:
          IP_ADDR: ${{ steps.run-gcp-instance.outputs.IP_ADDR }}
        run: |
          set -ex
          cd ansible
          python3 -m pip install -r python_modules.txt

          COSMIAN_VM_VERSION="last_build/${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}"

          export ANSIBLE_HOST_KEY_CHECKING=False
          for i in {1..2}
          do
            echo "Iteration: $i"
            ansible-playbook ${{ inputs.product }}-playbook.yml -i ${IP_ADDR}, -u cosmian -e cosmian_vm_version=$COSMIAN_VM_VERSION -e cosmian_kms_version=${{ inputs.kms-version }}
          done

      - name: Stop and delete GCP instance
        if: success() || failure() || cancelled()
        env:
          CI_INSTANCE: ${{ steps.env.outputs.ci_instance }}
        run: |
          set +e
          gcloud ${{ inputs.mode }} compute instances delete --quiet $CI_INSTANCE --zone ${{ inputs.zone }} --project $GCP_DEV_PROJECT
          gcloud compute firewall-rules delete ${CI_INSTANCE}-allow-ports-cli --quiet
          set -e

  release-image:
    name: Release image - ${{ inputs.distrib }} - ${{ inputs.techno }} - ${{ inputs.product }}
    if: startsWith(github.ref, 'refs/tags')
    runs-on: ubuntu-22.04
    needs: [build-image, test-image]
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: GCP auth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GOOGLE_COSMIAN_DEV_CREDENTIALS }}

      - name: Copy image to public project
        env:
          CI_INSTANCE: ${{ needs.build-image.outputs.ci_instance }}
          IMAGE_NAME: ${{ needs.build-image.outputs.image_name }}
          TAG: ${{ github.ref_name }}
          KMS: ${{ inputs.kms-version }}
        run: |
          set -ex

          VERSION=$(echo $TAG | sed 's/\./-/g; s/_/-/g; s/+/-/g')
          KMS_VERSION=$(echo $KMS | sed 's/\./-/g; s/_/-/g; s/+/-/g')
          NEW_IMAGE_NAME=cosmian-vm-$VERSION-${{ inputs.techno }}-${{ inputs.distrib }}

          if [ "${{ inputs.distrib }}" = "ubuntu" ]; then
            if [ "${{ inputs.product }}" = "cosmian-vm" ]; then
              LICENSE="${{ secrets.GCP_COSMIAN_VM_UBUNTU_LICENCE }}"
            else
              LICENSE=${{ secrets.GCP_KMS_UBUNTU_LICENSE }}
              NEW_IMAGE_NAME=cosmian-vm-${VERSION}-kms-${KMS_VERSION}-${{ inputs.techno }}-${{ inputs.distrib }}
            fi
          else
            if [ "${{ inputs.product }}" = "cosmian-vm" ]; then
              LICENSE="${{ secrets.GCP_COSMIAN_VM_RHEL_LICENCE }}"
            else
              LICENSE=${{ secrets.GCP_KMS_RHEL_LICENSE }}
              NEW_IMAGE_NAME=cosmian-vm-${VERSION}-kms-${KMS_VERSION}-${{ inputs.techno }}-${{ inputs.distrib }}
            fi
          fi

          gcloud ${{ inputs.mode }} compute --project=$GCP_DEV_PROJECT images create $NEW_IMAGE_NAME \
            --source-image=$IMAGE_NAME \
            --source-image-project=$GCP_DEV_PROJECT

          gcloud ${{ inputs.mode }} compute --project=$GCP_PUBLIC_PROJECT images create $NEW_IMAGE_NAME \
            --source-image=$IMAGE_NAME \
            --source-image-project=$GCP_DEV_PROJECT \
            --licenses=$LICENSE
