---
on:
  workflow_call:
  workflow_dispatch:

concurrency:
  group: marketplace_gcp

name: GCP base images build

jobs:
  image:
    strategy:
      fail-fast: false
      matrix:
        distrib: [ubuntu, rhel]
        product: [base-image]
        techno: [sev, tdx]
        exclude:
          - techno: tdx
            distrib: rhel
    name: (GCP) ${{ matrix.product }} - ${{ matrix.distrib }} - ${{ matrix.techno }}
    secrets: inherit
    uses: ./.github/workflows/gcp_base_image.yml
    with:
      techno: ${{ matrix.techno }}
      distrib: ${{ matrix.distrib }}
      product: ${{ matrix.product }}
      base-version: 0.1.6
