---
name: Build and test image for GCP SEV and TDX

on:
  workflow_call:
    inputs:
      distrib:
        required: true
        type: string
      machine-type:
        required: true
        type: string
      zone:
        required: true
        type: string
      confidential-compute-type:
        required: true
        type: string
      techno:
        required: true
        type: string
      min-cpu-platform:
        required: true
        type: string
      project:
        required: true
        type: string
      mode:
        required: true
        type: string
      maintenance:
        required: true
        type: string
      product:
        required: true
        type: string

env:
  GCP_DEV_PROJECT: cosmian-dev
  GCP_PUBLIC_PROJECT: cosmian-public

jobs:
  build-image:
    name: Packer build - ${{ inputs.distrib }} - ${{ inputs.techno }} - ${{ inputs.product }}
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      id-token: write
    defaults:
      run:
        working-directory: ./packer
    outputs:
      timestamp: ${{ steps.env.outputs.TIMESTAMP }}
      image_name: ${{ steps.env.outputs.IMAGE_NAME }}
      ci_instance: ${{ steps.env.outputs.CI_INSTANCE }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create env variables
        id: env
        run: |
          TIMESTAMP="$(date -u +'%Y%m%d%H%M%S')"
          echo "TIMESTAMP=$TIMESTAMP" >> "$GITHUB_OUTPUT"
          echo "IMAGE_NAME=temp-$TIMESTAMP-${{ inputs.product }}-${{ inputs.distrib }}-${{ inputs.techno }}" >> "$GITHUB_OUTPUT"
          echo "CI_INSTANCE=gh-ci-$TIMESTAMP-${{ inputs.product }}-${{ inputs.distrib }}-${{ inputs.techno }}" >> "$GITHUB_OUTPUT"

      - name: Setup packer
        uses: hashicorp/setup-packer@main

      - name: Install packer plugins
        run: |
          packer plugins install github.com/hashicorp/googlecompute
          packer plugins install github.com/hashicorp/ansible

      - name: Init packer
        run: |
          packer init ${{ inputs.product }}-gcp-${{ inputs.techno }}-${{ inputs.distrib }}.pkr.hcl

      - name: GCP auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GOOGLE_COSMIAN_DEV_CREDENTIALS }}

      - name: Packer build image
        id: packer-build
        env:
          TIMESTAMP: ${{ steps.env.outputs.TIMESTAMP }}
        run: |
          packer build -debug -var "prefix=temp-$TIMESTAMP" ${{ inputs.product }}-gcp-${{ inputs.techno }}-${{ inputs.distrib }}.pkr.hcl

  test-image:
    name: Test image - ${{ inputs.distrib }} - ${{ inputs.techno }} - ${{ inputs.product }}
    runs-on: ubuntu-22.04
    needs: build-image
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: GCP auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GOOGLE_COSMIAN_DEV_CREDENTIALS }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          version: latest
          install_components: ${{ inputs.mode }}

      - name: Launch GCP instance
        id: run-gcp-instance
        env:
          IMAGE_NAME: ${{ needs.build-image.outputs.image_name }}
          CI_INSTANCE: ${{ needs.build-image.outputs.ci_instance }}
        run: |
          set -ex
          gcloud ${{ inputs.mode }} compute instances create $CI_INSTANCE \
            --machine-type ${{ inputs.machine-type }} \
            --zone ${{ inputs.zone }} \
            --min-cpu-platform="${{ inputs.min-cpu-platform }}" \
            --confidential-compute-type=${{ inputs.confidential-compute-type }} \
            --image="$IMAGE_NAME" \
            --image-project=${{ inputs.project }} \
            --project ${{ inputs.project }} \
            --tags ssh-full,backend,backend-rust-full,http-server,https-server,cosmian-vm-agent,${{ inputs.product }} \
            --${{ inputs.maintenance }} \
            --metadata-from-file=startup-script=resources/scripts/${{ inputs.product }}-gcp-start-script.sh \
            --max-run-duration=10h \
            --instance-termination-action=DELETE
          IP_ADDR=$(gcloud beta compute instances describe $CI_INSTANCE --format='get(networkInterfaces[0].accessConfigs[0].natIP)' --zone=${{ inputs.zone }})
          echo "IP_ADDR=${IP_ADDR}" >> "$GITHUB_OUTPUT"

      - name: Download Cosmian VM CLI
        run: |
          wget https://package.cosmian.com/cosmian_vm/last_build/cosmian_vm

      - name: Change permissions of binaries
        run: |
          set -e
          chmod +x ./cosmian_vm

      - name: Test Cosmian VM Agent on GCP instance
        id: test_cosmian_vm
        env:
          CI_INSTANCE: ${{ needs.build-image.outputs.ci_instance }}
          IP_ADDR: ${{ steps.run-gcp-instance.outputs.IP_ADDR }}
        run: |
          set -ex
          bash resources/scripts/tests/${{ inputs.product }}-gcp_image.sh "${{ inputs.mode }}" "$CI_INSTANCE" "${{ inputs.zone }}" "$IP_ADDR"

      - name: Stop and delete GCP instance
        if: success()
        env:
          CI_INSTANCE: ${{ needs.build-image.outputs.ci_instance }}
        run: |
          set +e
          gcloud ${{ inputs.mode }} compute instances delete --quiet $CI_INSTANCE --zone ${{ inputs.zone }} --project ${{ inputs.project }}
          set -e

      - name: Delete GCP CI image
        if: startsWith(github.ref, 'refs/tags') != true
        env:
          IMAGE_NAME: ${{ needs.build-image.outputs.image_name }}
        run: |
          gcloud ${{ inputs.mode }} compute images delete --quiet $IMAGE_NAME

  release-image:
    name: Release image - ${{ inputs.distrib }} - ${{ inputs.techno }} - ${{ inputs.product }}
    if: startsWith(github.ref, 'refs/tags')
    runs-on: ubuntu-22.04
    needs: [build-image, test-image]
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: GCP auth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GOOGLE_COSMIAN_DEV_CREDENTIALS }}

      - name: Copy image to public project
        env:
          CI_INSTANCE: ${{ needs.build-image.outputs.ci_instance }}
          IMAGE_NAME: ${{ needs.build-image.outputs.image_name }}
        run: |
          TAG=${{  github.ref_name }}
          VERSION=$(echo $TAG | sed 's/\./-/g; s/_/-/g; s/+/-/g')
          NEW_IMAGE_NAME=${{ inputs.product }}-$VERSION-${{ inputs.techno }}-${{ inputs.distrib }}
          if [ "${{ inputs.distrib }}" = "ubuntu" ]; then
            if [ "${{ inputs.product }}" = "cosmian-vm" ]; then
              LICENSE="${{ secrets.GCP_COSMIAN_VM_UBUNTU_LICENCE }}"
            else
              LICENSE=${{ secrets.GCP_KMS_UBUNTU_LICENSE }}
            fi
          else
            if [ "${{ inputs.product }}" = "cosmian-vm" ]; then
              LICENSE="${{ secrets.GCP_COSMIAN_VM_RHEL_LICENCE }}"
            else
              LICENSE=${{ secrets.GCP_KMS_RHEL_LICENSE }}
            fi
          fi
          gcloud ${{ inputs.mode }} compute --project=$GCP_DEV_PROJECT images create $NEW_IMAGE_NAME \
            --source-image=$IMAGE_NAME \
            --source-image-project=$GCP_DEV_PROJECT

          gcloud ${{ inputs.mode }} compute --project=$GCP_PUBLIC_PROJECT images create $NEW_IMAGE_NAME \
            --source-image=$IMAGE_NAME \
            --source-image-project=$GCP_DEV_PROJECT \
            --licenses=$LICENSE
