---
name: Github Release

on:
  workflow_call:

jobs:
  release:
    name: Release binaries
    runs-on: [self-hosted, no-tee]

    steps:
      - name: Download binaries
        uses: actions/download-artifact@v4

      - name: Display artifacts content
        run: find .

      - name: Release on tags, attach asset on release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./cosmian_vm_ubuntu-22.04/home/runner/work/cosmian_vm/cosmian_vm/target/debian/cosmian-vm-agent_*-1_amd64.deb
            ./cosmian_vm_ubuntu-22.04/home/runner/work/cosmian_vm/cosmian_vm/target/debian/cosmian-vm_*-1_amd64.deb
            ./cosmian_vm_ubuntu-22.04/home/runner/work/cosmian_vm/cosmian_vm/target/generate-rpm/cosmian_vm-*-1.x86_64.rpm
            ./cosmian_vm_ubuntu-22.04/home/runner/work/cosmian_vm/cosmian_vm/target/generate-rpm/cosmian_vm_agent-*-1.x86_64.rpm
            ./cosmian_vm_ubuntu-24.04/home/runner/work/cosmian_vm/cosmian_vm/target/debian/cosmian-vm_*-1_amd64.deb
            ./cosmian_vm_ubuntu-24.04/home/runner/work/cosmian_vm/cosmian_vm/target/debian/cosmian-vm-agent_*-1_amd64.deb

  cleanup:
    name: Clean Github cache
    if: startsWith(github.ref, 'refs/tags/')
    uses: Cosmian/reusable_workflows/.github/workflows/cleanup_cache.yml@main
    secrets: inherit
