---
on:
  # Run only on pull requests and tags
  push:
    tags:
      - '*'
  pull_request:

name: Cloud providers

jobs:
  build-cosmian-vm-binaries:
    name: Build binaries
    uses: ./.github/workflows/build.yml

  # azure:
  #   needs: build-cosmian-vm-binaries
  #   uses: ./.github/workflows/azure_main.yml
  #   secrets: inherit

  # gcp:
  #   needs: build-cosmian-vm-binaries
  #   uses: ./.github/workflows/gcp_main.yml
  #   secrets: inherit

  aws:
    needs: build-cosmian-vm-binaries
    uses: ./.github/workflows/aws_main.yml
    secrets: inherit

  release:
    name: Release
    if: startsWith(github.ref, 'refs/tags/')
    needs:
      # - azure
      # - gcp
      - aws
    secrets: inherit
    uses: ./.github/workflows/release.yml
