---
name: Nightly Cloud providers

on:
  push:
    # any tags, including tags with / like v1.0/alpha
    tags:
      - '**'
  schedule:
    # every day at 0 AM
    - cron: 00 0 * * *
  workflow_dispatch:

jobs:
  build-cosmian-vm-binaries:
    name: Build binaries
    uses: ./.github/workflows/build.yml

  azure:
    needs: build-cosmian-vm-binaries
    uses: ./.github/workflows/nightly_azure_main.yml
    secrets: inherit

  gcp:
    needs: build-cosmian-vm-binaries
    uses: ./.github/workflows/nightly_gcp_main.yml
    secrets: inherit

  aws:
    needs: build-cosmian-vm-binaries
    uses: ./.github/workflows/nightly_aws_main.yml
    secrets: inherit

  release:
    name: Release
    if: startsWith(github.ref, 'refs/tags/')
    needs:
      - azure
      - gcp
      - aws
    secrets: inherit
    uses: ./.github/workflows/release.yml
