---
on:
  workflow_call:
  workflow_dispatch:

concurrency:
  group: marketplace_azure

name: Azure images nightly build

jobs:
  clean-resources:
    uses: ./.github/workflows/azure_clean.yml
    secrets: inherit

  sev-image:
    strategy:
      fail-fast: false
      matrix:
        distrib: [ubuntu, rhel]
        product: [cosmian-vm, kms, ai-runner]
    name: (AZURE) ${{ matrix.product }} - ${{ matrix.distrib }} - SEV
    needs:
      - clean-resources
    secrets: inherit
    uses: ./.github/workflows/azure_image.yml
    with:
      techno: sev
      distrib: ${{ matrix.distrib }}
      product: ${{ matrix.product }}
      kms-version: 4.16.0
      ai-runner-version: 0.3.0

  tdx-image:
    strategy:
      fail-fast: false
      matrix:
        distrib: [ubuntu]
        product: [cosmian-vm, kms, ai-runner]
    name: (AZURE) ${{ matrix.product }} - ${{ matrix.distrib }} - TDX
    needs:
      - clean-resources
    secrets: inherit
    uses: ./.github/workflows/azure_image.yml
    with:
      techno: tdx
      distrib: ${{ matrix.distrib }}
      product: ${{ matrix.product }}
      kms-version: 4.16.0
      ai-runner-version: 0.3.0

  sev-ansible:
    if: startsWith(github.ref, 'refs/tags/') != true
    strategy:
      fail-fast: false
      matrix:
        distrib: [ubuntu, rhel]
        product: [cosmian-vm, kms, ai-runner]
    name: (AZURE) ${{ matrix.product }} - ${{ matrix.distrib }} - SEV
    needs:
      - clean-resources
      - sev-image # to avoid reaching the Azure quota VM (20)
      - tdx-image # to avoid reaching the Azure quota VM (20)
    secrets: inherit
    uses: ./.github/workflows/azure_ansible.yml
    with:
      techno: sev
      distrib: ${{ matrix.distrib }}
      product: ${{ matrix.product }}
      kms-version: 4.16.0
      ai-runner-version: 0.3.0

  tdx-ansible:
    if: startsWith(github.ref, 'refs/tags/') != true
    strategy:
      fail-fast: false
      matrix:
        distrib: [ubuntu]
        product: [cosmian-vm, kms, ai-runner]
    name: (AZURE) ${{ matrix.product }} - ${{ matrix.distrib }} - TDX
    needs:
      - clean-resources
      - sev-image # to avoid reaching the Azure quota VM (20)
      - tdx-image # to avoid reaching the Azure quota VM (20)
    secrets: inherit
    uses: ./.github/workflows/azure_ansible.yml
    with:
      techno: tdx
      distrib: ${{ matrix.distrib }}
      product: ${{ matrix.product }}
      kms-version: 4.16.0
      ai-runner-version: 0.3.0

  post-clean-resources:
    if: success() || failure() || cancelled()
    needs:
      - sev-image
      - tdx-image
      - sev-ansible
      - tdx-ansible
    uses: ./.github/workflows/azure_clean.yml
    secrets: inherit
