---
on:
  workflow_call:
  workflow_dispatch:

concurrency:
  group: marketplace_azure

name: Nightly Azure images build

jobs:
  clean-resources:
    uses: ./.github/workflows/azure_clean.yml
    secrets: inherit

  image:
    strategy:
      fail-fast: false
      max-parallel: 3
      matrix:
        distrib: [ubuntu, rhel]
        product: [cosmian-vm, kms, ai-runner]
        techno: [sev, tdx]
        exclude:
          - product: ai-runner
            distrib: rhel
          - techno: tdx
            distrib: rhel
    name: (AZURE) ${{ matrix.product }} - ${{ matrix.distrib }} - ${{ matrix.techno }}
    needs:
      - clean-resources
    secrets: inherit
    uses: ./.github/workflows/azure_image.yml
    with:
      techno: ${{ matrix.techno }}
      distrib: ${{ matrix.distrib }}
      product: ${{ matrix.product }}
      kms-version: 4.16.0
      ai-runner-version: 0.3.0
      base-version: 0.1.4

  ansible:
    if: startsWith(github.ref, 'refs/tags/') != true
    strategy:
      fail-fast: false
      max-parallel: 3
      matrix:
        distrib: [ubuntu, rhel]
        product: [cosmian-vm, kms, ai-runner]
        techno: [sev, tdx]
        exclude:
          - product: ai-runner
            distrib: rhel
          - techno: tdx
            distrib: rhel
    name: (AZURE) ${{ matrix.product }} - ${{ matrix.distrib }} - ${{ matrix.techno }}
    needs:
      - clean-resources
    secrets: inherit
    uses: ./.github/workflows/azure_ansible.yml
    with:
      techno: ${{ matrix.techno }}
      distrib: ${{ matrix.distrib }}
      product: ${{ matrix.product }}
      kms-version: 4.16.0
      ai-runner-version: 0.3.0

  post-clean-resources:
    if: success() || cancelled()
    needs:
      - image
      - ansible
    uses: ./.github/workflows/azure_clean.yml
    secrets: inherit
