---
on:
  # Run only on pull requests and tags
  push:
    tags:
      - '*'
  pull_request:

concurrency:
  group: marketplaces

name: Pull requests CI

jobs:
  build-cosmian-vm-binaries:
    name: Build binaries
    uses: ./.github/workflows/build.yml

  clean-azure-resources:
    name: Clean CI Azure resources
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Az CLI login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDS_JSON }}

      - name: Delete any existing CI Azure resources
        run: |
          set +e
          bash .github/scripts/azure-delete-ci-resources.sh

  build-test-gcp-sev-image:
    strategy:
      fail-fast: false
      matrix:
        distrib: [ubuntu, rhel]
        product: [cosmian-vm, kms]
    name: (GCP) ${{ matrix.product }} - ${{ matrix.distrib }} - SEV
    needs: build-cosmian-vm-binaries
    secrets: inherit
    uses: ./.github/workflows/gcp_image.yml
    with:
      techno: sev
      distrib: ${{ matrix.distrib }}
      machine-type: n2d-standard-2
      zone: europe-west4-a
      confidential-compute-type: SEV_SNP
      min-cpu-platform: AMD Milan
      project: cosmian-dev
      mode: beta
      product: ${{ matrix.product }}
      kms-version: 4.16.0

  build-test-azure-sev-image:
    strategy:
      fail-fast: false
      matrix:
        distrib: [ubuntu, rhel]
        product: [cosmian-vm, kms]
    name: (AZURE) ${{ matrix.product }} - ${{ matrix.distrib }} - SEV
    needs:
      - build-cosmian-vm-binaries
      - clean-azure-resources
    secrets: inherit
    uses: ./.github/workflows/azure_image.yml
    with:
      techno: sev
      distrib: ${{ matrix.distrib }}
      product: ${{ matrix.product }}
      kms-version: 4.16.0

  release:
    name: Release
    if: startsWith(github.ref, 'refs/tags/')
    needs: [build-test-gcp-sev-image, build-test-azure-sev-image]
    secrets: inherit
    uses: ./.github/workflows/release.yml
