---
on:
  # Run only on pull requests
  pull_request:

name: Pull request

jobs:
  cleanup: # we remove the Github cache to avoid any conflict
    name: Clean Github cache
    uses: Cosmian/reusable_workflows/.github/workflows/cleanup_cache.yml@main
    secrets: inherit

  build-cosmian-vm-binaries:
    needs: cleanup
    name: Build binaries
    uses: ./.github/workflows/build_all.yml

  azure:
    needs: build-cosmian-vm-binaries
    uses: ./.github/workflows/azure_main.yml
    with:
      product: cosmian-vm
      kms-version: 5.0.0
      ai-runner-version: 1.0.0
      techno: sev
    secrets: inherit

  gcp:
    needs: build-cosmian-vm-binaries
    uses: ./.github/workflows/gcp_main.yml
    with:
      product: cosmian-vm
      kms-version: 5.0.0
      ai-runner-version: 1.0.0
      techno: sev
    secrets: inherit

  # Too many failures when rebooting EC2
  # aws:
  #   needs: build-cosmian-vm-binaries
  #   uses: ./.github/workflows/aws_main.yml
  #   with:
  #     product: cosmian-vm
  #     kms-version: 5.0.0
  #     ai-runner-version: 1.0.0
  #     techno: sev
  #   secrets: inherit

  release:
    name: Release
    needs:
      - azure
      - gcp
      # - aws
    secrets: inherit
    uses: ./.github/workflows/github_release.yml
