---
name: Release

on:
  workflow_call:

jobs:
  release:
    name: Release binaries
    runs-on: [self-hosted, no-tee]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download binaries
        uses: actions/download-artifact@v4
        with:
          name: cosmian_vm

      - name: Release on tags, attach asset on release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            target/release/cosmian_vm_agent
            target/release/cosmian_vm
            target/release/cosmian_certtool

  cleanup:
    uses: Cosmian/reusable_workflows/.github/workflows/cleanup_cache.yml@main
    secrets: inherit
