---
name: Release

on:
  workflow_call:

jobs:
  release:
    name: Release binaries
    runs-on: [self-hosted, no-tee]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download binaries
        uses: actions/download-artifact@v4
        with:
          name: cosmian_vm

  cleanup:
    if: startsWith(github.ref, 'refs/tags/')
    uses: Cosmian/reusable_workflows/.github/workflows/cleanup_cache.yml@main
    secrets: inherit
