name: Release

on:
  workflow_call:

jobs:
  release:
    name: Release binaries
    runs-on: [self-hosted, no-tee]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download binaries
        uses: actions/download-artifact@v4
        with:
            name: cosmian_vm

      - name: GH Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            target/release/cosmian_vm_agent
            target/release/cosmian_vm
            target/release/cosmian_certtool
            resources/scripts/cosmian_fstool

      - name: Push latest build to package.cosmian.com
        run: |
          set -x
          DESTINATION_DIR=/mnt/package/cosmian_vm/last_build/
          ssh cosmian@package.cosmian.com mkdir -p $DESTINATION_DIR
          scp target/release/cosmian_vm_agent target/release/cosmian_vm target/release/cosmian_certtool resources/scripts/cosmian_fstool cosmian@package.cosmian.com:$DESTINATION_DIR/

      - name: Push version tag to package.cosmian.com
        if: startsWith(github.ref, 'refs/tags/')
        env:
            VERSION: ${{ github.ref_name }}
        run: |
          set -x
          DESTINATION_DIR=/mnt/package/cosmian_vm/$VERSION
          ssh cosmian@package.cosmian.com mkdir -p $DESTINATION_DIR
          scp target/release/cosmian_vm_agent target/release/cosmian_vm target/release/cosmian_certtool cosmian@package.cosmian.com:$DESTINATION_DIR/
